version: '3'

tasks:
  init:
    cmds:
      - >
        docker run --rm   -u "$(id -u):$(id -g)"   -v "$(pwd):/var/www/html"   -w /var/www/html
        laravelsail/php82-composer:latest composer install --ignore-platform-req=ext-gd --ignore-platform-req=ext-exif
      - ./vendor/bin/sail up -d
      - ./vendor/bin/sail npm install
      - ./vendor/bin/sail npm run production
      - cp .env.local .env
      - ./vendor/bin/sail artisan key:generate
      - ./vendor/bin/sail artisan make:database

  up:
    cmds:
      - ./vendor/bin/sail up -d

  down:
    cmds:
      - ./vendor/bin/sail down

  refresh:
    cmds:
      # - NOTE: THE ORDER IS IMPORTANT !!"
      - ./vendor/bin/sail artisan migrate:fresh --path="database/migrations/admsys" --database=db_auth
      - ./vendor/bin/sail artisan migrate:fresh --path="database/migrations/db_nomadelfia" --database=db_nomadelfia --drop-views
      - ./vendor/bin/sail artisan migrate:fresh --path="database/migrations/scuola" --database=db_scuola
      - ./vendor/bin/sail artisan migrate:fresh --path="database/migrations/biblioteca" --database=db_biblioteca --drop-views
      - ./vendor/bin/sail artisan migrate:fresh --path="database/migrations/patente" --database=db_patente --drop-views
      - ./vendor/bin/sail artisan migrate:fresh --path="database/migrations/officina" --database=db_officina
      - ./vendor/bin/sail artisan migrate:fresh --path="database/migrations/foto" --database=db_foto
      - ./vendor/bin/sail artisan migrate:fresh --path="database/migrations/rtn" --database=db_rtn
      - ./vendor/bin/sail artisan migrate:fresh --path="database/migrations/agraria" --database=db_agraria
      # - seed tables
      - ./vendor/bin/sail artisan db:seed

  clear:
    cmds:
      - ./vendor/bin/sail php artisan config:clear
      - ./vendor/bin/sail php artisan route:clear
      - ./vendor/bin/sail php artisan view:clear

  qa:
    cmds:
      - task lint:check
      - task analyse
      - task test

  test:
    deps: [up]
    cmds:
      - ./vendor/bin/sail pest --bail

  test:ci:
    cmds:
      - ./vendor/bin/pest
    env:
      APP_ENV: ci

  lint:check:ci:
    cmds:
      - ./vendor/bin/pint --test
      - npm run format:check
      - ./vendor/bin/rector --dry-run


  lint:check:
    cmds:
      - ./vendor/bin/sail pint --test
      - ./vendor/bin/sail npm run format:check
      - ./vendor/bin/sail bin rector --dry-run

  lint:
    cmds:
      - ./vendor/bin/sail pint
      - ./vendor/bin/sail npm run format:write
      - ./vendor/bin/sail bin rector

  analyse:
    cmds:
      - ./vendor/bin/sail bin phpstan analyse

  analyse:baseline:
    cmds:
      - ./vendor/bin/sail bin phpstan analyse  --generate-baseline

  analyse:ci:
    cmds:
       - ./vendor/bin/phpstan analyse
