version: '3'

tasks:
  init:
    cmds:
      - >
        docker run --rm   -u "$(id -u):$(id -g)"   -v "$(pwd):/var/www/html"   -w /var/www/html
        laravelsail/php81-composer:latest composer install --ignore-platform-req=ext-gd --ignore-platform-req=ext-exif
      - ./vendor/bin/sail up -d
      - ./vendor/bin/sail npm install
      - ./vendor/bin/sail npm run production
      - ./vendor/bin/sail artisan make:database

  up:
    cmds:
      - ./vendor/bin/sail up -d

  down:
    cmds:
      - ./vendor/bin/sail down

  refresh:
    cmds:
      # - NOTE: THE ORDER IS IMPORTANT !!"
      - ./vendor/bin/sail artisan migrate:fresh --path="database/migrations/admsys" --database=db_auth
      - ./vendor/bin/sail artisan migrate:fresh --path="database/migrations/db_nomadelfia" --database=db_nomadelfia
      - ./vendor/bin/sail artisan migrate:fresh --path="database/migrations/scuola" --database=db_scuola
      - ./vendor/bin/sail artisan migrate:fresh --path="database/migrations/biblioteca" --database=db_biblioteca
      - ./vendor/bin/sail artisan migrate:fresh --path="database/migrations/patente" --database=db_patente
      - ./vendor/bin/sail artisan migrate:fresh --path="database/migrations/officina" --database=db_officina
      - ./vendor/bin/sail artisan migrate:fresh --path="database/migrations/foto" --database=db_foto
      - ./vendor/bin/sail artisan migrate:fresh --path="database/migrations/rtn" --database=db_rtn
      # - seed tables
      - ./vendor/bin/sail artisan db:seed

  clear:
    cmds:
      - ./vendor/bin/sail  php artisan config:clear
      - ./vendor/bin/sail  php artisan route:clear

  test:
    deps: [up]
    cmds:
      - ./vendor/bin/sail  test --stop-on-error "$@"

  test:ci:
    cmds:
      - ./vendor/bin/pest

  lint:
    cmds:
      - docker run -it --rm -v $PWD:/workspace syncloudsoftech/pinter  ./vendor/bin/pint
      - ./vendor/bin/sail npm run format:write

  lint:check:
    cmds:
      - ./vendor/bin/pint --test
      - npm run format:check

  analyse:
    cmds:
      - ./vendor/bin/phpstan analyse  -l 2
