CREATE TABLE `dbf_dia120_enrico` (
  `datnum` varchar(10) NOT NULL,
  `anum` varchar(8) NOT NULL,
  `cddvd` varchar(10) NOT NULL,
  `hdint` varchar(10) NOT NULL,
  `hdext` varchar(10) NOT NULL,
  `sc` varchar(2) NOT NULL,
  `fi` varchar(2) NOT NULL,
  `tp` varchar(2) NOT NULL,
  `nfo` int(11) DEFAULT NULL,
  `data` date DEFAULT NULL,
  `localita` text NOT NULL,
  `argomento` text NOT NULL,
  `descrizione` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
