# For more information: https://laravel.com/docs/sail
version: '3'
services:
    laravel.test:
        build:
            context: ./vendor/laravel/sail/runtimes/7.4
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-7.4-ok/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
#            - '${APP_PORT:-8080}:80'
            - '8080:80'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - mysql
            - meilisearch
    mysql:
        image: mariadb:10.4
        container_name: db
        restart: unless-stopped
        tty: true
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_DATABASE: root
            MYSQL_ROOT_PASSWORD: root
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - 'sail-mysql:/var/lib/mysql'
        networks:
            - sail
#    mysql:
#        image: 'mysql/mysql-server:8.0'
##        ports:
##            - '${FORWARD_DB_PORT:-3306}:3306'
#        environment:
#            MYSQL_ROOT_PASSWORD: 'root'
#            MYSQL_ROOT_HOST: "root"
##            MYSQL_DATABASE: '${DB_DATABASE}'
##            MYSQL_USER: '${DB_USERNAME}'
##            MYSQL_PASSWORD: '${DB_PASSWORD}'
##            MYSQL_ALLOW_EMPTY_PASSWORD: 1
#        volumes:
#            - 'sail-mysql:/var/lib/mysql'
#        networks:
#            - sail
#        healthcheck:
#            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
#            retries: 3
#            timeout: 5s
    phpmyadmin:
        image: phpmyadmin:5.2.0-apache
        restart: always
        ports:
            - "8081:80"
        environment:
            - PMA_HOST=mysql
            - PMA_USER=root
            - PMA_PASSWORD=root
        networks:
            - sail
    meilisearch:
        image: 'getmeili/meilisearch:latest'
        ports:
            - '${FORWARD_MEILISEARCH_PORT:-7700}:7700'
        volumes:
            - 'sail-meilisearch:/data.ms'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "wget", "--no-verbose", "--spider",  "http://localhost:7700/health"]
            retries: 3
            timeout: 5s
networks:
    sail:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
    sail-meilisearch:
        driver: local
