-- Run the migrations

# | Servidor: 192.168.11.13:8080
# | MySQL Version: 5.5.5-10.1.38-MariaDB
# | PHP Version: 5.6.40

# ISSUE 1:
#  After reviewing MySQL 5.7 changes, MySql stopped supporting zero values in date / datetime.
#  Its incorrect to use zeros in date or in datetime, just put null instead of zeros.
#  Solution: SET to NULL all the data equal to  '0000-00-00'


CREATE TABLE `arch_prof` (
 `Id_regpro` int(11) NOT NULL AUTO_INCREMENT COMMENT 'identificatore DB',
 `Id_ap` int(11) NOT NULL COMMENT 'Identificatore Film',
 `Fonte` enum('Hard-Disk','','DVD') NOT NULL COMMENT 'Dispositivo Magnetico',
 `Categoria_ap` enum('', 'BD','BV','DB','DV','DVR','HD','NB','ND','NR','NS','S8','16M','8M') NOT NULL COMMENT 'Serie',
 `Numero_ap` int(5) NOT NULL COMMENT 'Numero',
 `Numreg` int(5) NOT NULL COMMENT 'Numero de registrazione',
 `Min_Ini` int(5) NOT NULL COMMENT 'Minuti Inizio',
 `Min_fin` int(5) NOT NULL COMMENT 'Minuti Fine',
 `Datareg` date NOT NULL COMMENT 'Date Registrazione',
 `Localita` varchar(400) NOT NULL COMMENT 'Localita',
 `Caratt` varchar(200) NOT NULL COMMENT 'Caratteristiche',
 `ca_k` varchar(1) NOT NULL COMMENT 'lettera k',
 `Mic` varchar(30) NOT NULL COMMENT 'Espazio Bianco',
 `ULTrasm` date DEFAULT NULL COMMENT 'Data Trasmisione',
 `Formato_reg` varchar(100) NOT NULL COMMENT 'Formato de Registrazione',
 `Dur_Nastro` int(11) NOT NULL COMMENT 'Minuti totale',
 `Sot_Categ` varchar(4) NOT NULL COMMENT 'Catalogo',
 `Min_tot` int(11) NOT NULL COMMENT 'Minuti totali',
 `Descrizione_ap` text NOT NULL COMMENT 'Descrizione',
 `Operatore` varchar(200) NOT NULL COMMENT 'Operatore telecamera',
 `estato` enum('0','1') NOT NULL,
 PRIMARY KEY (`Id_regpro`),
 UNIQUE KEY `Id_ap` (`Id_ap`,`Fonte`,`Categoria_ap`,`Numero_ap`,`Numreg`,`Min_Ini`,`Min_fin`,`Datareg`,`Descrizione_ap`(50)) USING BTREE,
 KEY `Categ` (`Sot_Categ`),
 KEY `Datareg` (`Datareg`),
 KEY `Localita` (`Localita`(255)),
 KEY `Caratt` (`Caratt`),
 KEY `Operatore` (`Operatore`),
 KEY `Descrizione_ap` (`Descrizione_ap`(255)),
 KEY `Datareg_2` (`Datareg`)
) ENGINE=InnoDB AUTO_INCREMENT=13920 DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT;

INSERT INTO `arch_prof` VALUES ('13783', '0', 'Hard-Disk', '', '0', '1', '0', '2', '2023-08-05', 'LISBONA', ' EDIUS', '', '', NULL, ' MP4', '0', 'NDDE', '2', 'NEWS 05 AGOSTO 2023 GMG - GMG LISBON - GIOVANNI A, SARA G, SAMUELE G, DIANA F VERONICA E, ELISA L, MIRIAM F, MARIA Z', 'JOSE J', '0');
INSERT INTO `arch_prof` VALUES ('13784', '0', 'Hard-Disk', '', '0', '1', '0', '6', '2023-08-05', 'FOTO VARIE, VIDEO', ' EDIUS', '', '', NULL, ' MP4', '0', 'NRGE', '6', 'GRAZIE CARLINO 90 ANNI - 90MO CARLINO - CARLINO, CARLO M, DON ZENO, MASSIMO M, FRANCESCO A, IRENE, MONICA CM, FIORELLA ', 'NICO', '0');

# INSERT INTO `arch_prof` VALUES ('13785', '0', 'Hard-Disk', '', '0', '1', '0', '13', '2023-08-07', 'NOMADELFIA ROSELLANA', ' DJI POCKET 2', '', '', '0000-00-00', ' H.264', '0', 'NRFE', '13', 'COMPLEANNO CARLINO - 90 ANNI  - DOTT. CAPPELLI, DON FERDINANDO, TIZIANA F, MILVA, FEDERICO E, MAURIZIO C, ROSELLA A, ENRICO, ING. MASSIMO MAULO, LIVIO, LUISA P, PIETRO L, PAOLO E, TOMMASO N, DON NICOLA, ARIEL, AMOS P, FRANCESCO Z, SILVIA Z, MARIETTO, ANTONELLO, ISACCO P, STEFANO Z, ', 'NICO', '0');
# INSERT INTO `arch_prof` VALUES ('13786', '0', 'Hard-Disk', '', '0', '1', '0', '4', '2023-08-01', 'LISBONA', ' SONY AX-53', '', '', '0000-00-00', ' MP4', '0', 'NRGE', '4', 'GMG LISBONA - GMG - GABRIEL A, GIOVANNI Z, DIANA, ARIS, LUCA A, SIMONE L, DARIO L, TARCISIO M, DANIELE PA, SAMUELE C', 'JOSEF, MARCO F, SAMUELE G', '0');
# INSERT INTO `arch_prof` VALUES ('13787', '0', 'Hard-Disk', '', '0', '1', '0', '5', '2023-08-02', 'LISBONA', ' SONY AX-53', '', '', '0000-00-00', ' MP4', '0', 'NRGE', '5', 'GMG LISBONA - GMG - DON STEFANO PAPINI, AGNESE A, TARCISIO M, PAOLO F, VERONICA E, SARA G', 'JOSEF, MARCO F, SAMUELE G', '0');
# INSERT INTO `arch_prof` VALUES ('13788', '0', 'Hard-Disk', '', '0', '1', '0', '7', '2023-08-03', 'LISBONA', ' SONY AX-53', '', '', '0000-00-00', ' MP4', '0', 'NRGE', '7', 'GMG LISBONA - GMG - ELENA Z, ELENA F, MARCO F, MARIA Z, DILETTA, PAOLO F, SARA G, SIMONE L, MARISA F, SAMUELE G, SARA M, GIOVANNI A, DOROTEA', 'JOSEF, MARCO F, SAMUELE G', '0');
# INSERT INTO `arch_prof` VALUES ('13789', '0', 'Hard-Disk', '', '0', '1', '0', '5', '2023-08-04', 'LISBONA', ' SONY AX-53', '', '', '0000-00-00', ' MP4', '0', 'NRGE', '5', 'GMG LISBONA - GMG - DOROTEA, DANIELE PA, GIOVANNI Z, VERONICA E, MARISA F, GIOVANNI A, SAMUELE G, SAMUELE CH, DARIO L, ARIS, MARIA Z, NOEMI', 'JOSEF, MARCO F, SAMUELE G', '0');
# INSERT INTO `arch_prof` VALUES ('13790', '0', 'Hard-Disk', '', '0', '1', '0', '4', '2023-08-05', 'LISBONA', ' SONY AX-53', '', '', '0000-00-00', ' MP4', '0', 'NRGE', '4', 'GMG LISBONA - GMG - SAMUELE C, PAOLO F, MATTEO M, MARIA FIORE, NOEMI, MARIA Z, ELISA L, DARIO L, DAMIANO L, AGNESE A, DIANA, SAMUEL M, MARCO F, GIOVANNI A, GIULIA A', 'JOSEF, MARCO F, SAMUELE G', '0');
# INSERT INTO `arch_prof` VALUES ('13791', '0', 'Hard-Disk', '', '0', '1', '0', '19', '2023-08-06', 'LISBONA', ' SONY AX-53', '', '', '0000-00-00', ' MP4', '0', 'NRGE', '19', 'GMG LISBONA - GMG - SAMUELE C, GIOVANNI Z, MARIA Z, DARIO L, MATTEO M, ARIS, SOFIA F, DANIELE PA, DOROTEA, SARA G, MARCO F, TARCISIO M, LUCA A, SARA M, MARIA FIORE, DIANA F, VERONICA E, MARISA F, GABRIEL A, GIULIA A, GIOVANNI A, SAMUELE CH, DILETTA, ARIS, NOEMI, DARIO L, ELENA F', 'JOSEF, MARCO F, SAMUELE G', '0');
# INSERT INTO `arch_prof` VALUES ('13792', '0', 'Hard-Disk', '', '0', '1', '0', '3', '2023-07-25', 'NOMADELFIA', ' SONY AX-53', '', '', '0000-00-00', ' MP4', '0', 'NRGE', '3', 'PARTENZA PER LA GMG DI LISBONA - GMG - JOY, DAMIANO L, SAMUEL M, TARCISIO M, DON FERDINANDO, GIANCARLO, DANIELE PA, ELENA Z', 'JOSEF, MARCO F, SAMUELE G', '0');
# INSERT INTO `arch_prof` VALUES ('13793', '0', 'Hard-Disk', '', '0', '1', '0', '6', '2023-07-25', 'SPAGNA, PORTOGALLO', ' SONY AX-53', '', '', '0000-00-00', ' MP4', '0', 'NRGE', '6', 'GMG DI LISBONA - ARRIVO A LUOLE - SAMUELE C, ARIS, DARIO L, NOEMI, DOROTEA, SARA M, VERONICA E, SIMONE A', 'JOSEF, MARCO F, SAMUELE G', '0');
# INSERT INTO `arch_prof` VALUES ('13794', '0', 'Hard-Disk', '', '0', '1', '0', '27', '2023-07-27', 'PORTOGALLO', ' SONY AX-53', '', '', '0000-00-00', ' MP4', '0', 'NRGE', '27', 'GMG DI LISBONA - LOULE - MATTEO M, LUCA A, PAOLO F, GIOVANNI A, DILETTA, MARCO F, NOEMI, MARISA F, SAMUELE CH, SARA G, ARIS, ELENA Z, AGNESE A, SARA M, MARIA FIORE, STEFAN, GIULIA A, DIANA, DOROTEA, VERONICA E, DON STEFANO PAPINI ', 'JOSEF, MARCO F, SAMUELE G', '0');
# INSERT INTO `arch_prof` VALUES ('13795', '0', 'Hard-Disk', '', '0', '1', '0', '10', '2023-07-28', 'PORTOGALLO', ' SONY AX-53', '', '', '0000-00-00', ' MP4', '0', 'NRGE', '10', 'GMG DI LISBONA - LOULE FESTA - GIOVANNI Z, PAOLO F, MARISA F, VERONICA E, ELENA Z, DIANA, MARIA FIORE, AGNESE, JOSEF, DILETTA, SAMUELE C', 'JOSEF, MARCO F, SAMUELE G', '0');
# INSERT INTO `arch_prof` VALUES ('13796', '0', 'Hard-Disk', '', '0', '1', '0', '10', '2023-07-29', 'PORTOGALLO', ' SONY AX-53', '', '', '0000-00-00', ' MP4', '0', 'NRGE', '10', 'GMG DI LISBONA - LOULE PARCO GIOCHI - ARIS, SARA G, DOROTEA, MARISA, NOEMI, SAMUELE C, JOSEF, MARIA FIORE, ELENA F, DARIO L, PAOLO F, ELENA Z, SARA G, SAMUELE G, SAMUELE CH, MARCO F', 'JOSEF, MARCO F, SAMUELE G', '0');
# INSERT INTO `arch_prof` VALUES ('13797', '0', 'Hard-Disk', '', '0', '1', '0', '20', '2023-07-30', 'PORTOGALLO', ' SONY AX-53', '', '', '0000-00-00', ' MP4', '0', 'NRGE', '20', 'GMG DI LISBONA - LOULE MESSA STADIO E CONCERTO - JOSEF, MATTEO M, DAMIANO L, PAOLO F, MARISA F, SAMUELE CH, DOROTEA, SARA G, VERONICA E, DON STEFANO PAPINI,  GIOVANNI A, ELENA F, LUCA A, NOEMI, ARIS', 'JOSEF, MARCO F, SAMUELE G', '0');
# INSERT INTO `arch_prof` VALUES ('13798', '0', 'Hard-Disk', '', '0', '1', '0', '20', '2023-07-31', 'PORTOGALLO', ' SONY AX-53', '', '', '0000-00-00', ' MP4', '0', 'NRGE', '20', 'GMG DI LISBONA - GMG - SAMUELE G, DIANA, GABRIEL A, PAOLO F, DILETTA, MARCO F', 'JOSEF, MARCO F, SAMUELE G', '0');
# INSERT INTO `arch_prof` VALUES ('13799', '0', 'Hard-Disk', '', '0', '1', '0', '53', '2023-08-02', 'NOMADELFIA', ' SONY FS5-K', '', '', '0000-00-00', ' MXF', '0', 'NRCU', '53', 'CONCERTO MONARI - SALA DON ZENO - ROBERTO N, CINZIA MONARI, PAOLO MARI, MAESTRO MONARI', 'NICO', '0');
# INSERT INTO `arch_prof` VALUES ('13800', '0', 'Hard-Disk', '', '0', '1', '0', '5', '2023-08-11', 'CECINA, SCUOLA MEDIA GALILEO GALILEI', ' SONY AX-53', '', '', '0000-00-00', ' MP4', '0', 'NRGE', '5', 'CAMPEGGIO CECINA - MONTAGGIO - DAVIDE G, GABRIELE Z, FEDERICO E, CYRIL, MATTEO M, ARIS, NICO, MILVA, AGNESE A, MARIA FIORE, SARA G, DIANA, LETIZIA S, BETARICE F, MAURICE, CARSLO S, DANIELE S, JOSEF, SAMUELE G, TARCISIO M, ISAIA, ELENA Z, CRISTINA A, STEFAN L, ROBERTO N, ODETTE', 'JOSE J', '0');
# INSERT INTO `arch_prof` VALUES ('13801', '0', 'Hard-Disk', '', '0', '1', '0', '8', '2023-08-12', 'CECINA, SCUOLA MEDIA GALILEO GALILEI', ' SONY AX-53', '', '', '0000-00-00', ' MP4', '0', 'NRGE', '8', 'CAMPEGGIO CECINA - PRANZO E ARRIVO BAMBINI - BENEDETTO M, CYRIL, GIOVANI Z, ENRICO GENOVESI, FEDERERICO E, MARCO O, MILVA, DANIELE S, ASI,A LUCA V, ARIS, ANGELO A, ELISA L, RECHELE, DAMIANO E, PAOLO F, IRENE P, GLORIA, SEBASTIANO, DONANTA L, SERENA A, DONATELLA S, MARISA F, NATAN, LINO E, SAMUELE M, SARA G, ALI, ARIEL, DAMIANO E, GIGLIELMO E, GIOVANNI A, NICO', 'NICO', '0');
# INSERT INTO `arch_prof` VALUES ('13802', '0', 'Hard-Disk', '', '0', '1', '0', '43', '2023-08-13', 'CECINA VADA, PIAZZA GIUSEPPE GARIBALDI', ' SONY AX-53', '', '', '0000-00-00', ' MP4', '0', 'NSSE', '43', 'MESSA E SEARATA A VADA - MESSA AL DUOMO DI CECINA, SERATA - MILVA, FRENCESCO Z, MARGHERITA S, GIOLE M, GLORIA P, FEDERICO EV, DARIO S, DENISA, TECLA, MARIA FIORE, ERIK, MANUEL, BENEDETTO M, ROBERTO N, ARIS, ELIA V, MARCO F, DOROTEA, SARA G, SAMUELE G, SIMONE L, LUCA A, AZZURRA, DILETTA, MARISA, FRENCESCA G, DAVIDE P, IRENE P, BEATRICE F, DOROTEA, SARA G, SARA M, ARIANNA, SAMUELE CH, ELIA V, GIOVANNI Z, DIANA, NOEMI, BEATRICE F, SAMUELE G, AGNESE A, MARCO F, JOSEF, SIMONE A, DILETTA, FEDERICO E, ASIA, ELENA F, GIOELE M, GIULIA A, ARIAL, MAURICE, DARIO L, ELISABETTA, DAVIDE G, DONATA L, ALI, EMANUELE Z ', 'JOSE J', '0');
# INSERT INTO `arch_prof` VALUES ('13803', '0', 'Hard-Disk', '', '0', '1', '0', '1', '2023-08-14', 'TANZANIA', ' CELLULARE', '', '', '0000-00-00', ' MP4', '0', 'NRTZ', '1', '2023_08_14 WHATSAPP VIDEO 2023-08-14 AT 17.54.21 - SALUTI PER FESTA ASSUNATA - MARIO A, ANGELA M, EMMANUELE M, MARIA CM, ZENO F, BIMBI DELLA TANZANIA', 'ALTRO', '0');
# INSERT INTO `arch_prof` VALUES ('13805', '0', 'Hard-Disk', '', '0', '1', '0', '1', '2023-08-14', 'CECINA, PIAZZA GIUSEPPE GARIBALDI, TANZANIA', ' EDIUS', '', '', '0000-00-00', ' MP4', '0', 'NSSE', '1', 'NEWS 14 AGOSTO 2023 INTERVISTE HIGHLIGHTS - SALUTI TANZANIA, SERATA INTERVISTE CECINA - MILVA, FRENCESCO Z, MARGHERITA S, GIOLE M, GLORIA P, DARIO S, DENISA, TECLA, MARIA FIORE, ERIK, MANUEL, BENEDETTO M, ARIS, ELIA V, MARCO F, DOROTEA, SARA G, SAMUELE G, SIMONE L, LUCA A, AZZURRA, DILETTA, MARISA, FRENCESCA G, IRENE P, BEATRICE F, DOROTEA, SARA G, SARA M, ARIANNA, SAMUELE CH, ELIA V, GIOVANNI Z, DIANA, BEATRICE F, SAMUELE G, AGNESE A, MARCO F, JOSEF, SIMONE A,  ASIA, ELENA F, GIOELE M, GIULIA A, ARIAL, MAURICE, DARIO L, ELISABETTA, DAVIDE G, DONATA L, ALI, EMANUELE Z', 'NICO - JOSE J', '0');
# INSERT INTO `arch_prof` VALUES ('13806', '0', 'Hard-Disk', '', '0', '1', '0', '30', '2023-08-15', 'CECINA', ' SONY AX-53', '', '', '0000-00-00', ' MP4', '0', 'NRFE', '30', 'FESTA ASSUNTA (CECINA) - GIOCCHI BIMBI, ADULTI - JOSEF, DARIO L, MARCO F, GIULIA A, LUCA A, BEATRICE F, MAURICE, MARIA FIORE, SARA M, GIOLE M, ARIEL, AMOS P, CATHERIN E, ISACCO P, ARIANNA, MARGHERITA S, GLORIA, FEDERICO E, DIANA, ELENA Z, MARISA, ARIS, GIOVANNI Z, CYRIL, STEFAN L, MANUEL Z, MILVA, DAMIANO E, LUCA R, SARA G, NICO, ODETTE, NOEMI, PAOLO F, MAROC O, ELENA F, ZENO S, DOROTEA, SERENA A, MISALE, DANIELE N, DONATA, ISAIA, BENEDETTO M', 'JOSE J', '0');
# INSERT INTO `arch_prof` VALUES ('13807', '0', 'Hard-Disk', '', '0', '1', '0', '80', '2023-06-12', 'ROMA', ' SONY AX-53', '', '', '0000-00-00', ' 2K XAVC S HD', '0', 'NDIN', '80', 'PRESENTAZIONE LIBRO - ONLINE LOVE - L AMORE AI TEMPI DEI SOCIAL. UN MANUALE DI SOPRAVVIVENZA DI TONINO CANTELMI PAOLA POLIDORO - GIORGIO GIBERTINI, FRANCESCO DI NOMADELFIA, PIETRO L', 'ALTRO', '0');
# INSERT INTO `arch_prof` VALUES ('13808', '0', 'Hard-Disk', '', '0', '1', '0', '10', '2023-06-11', 'ROMA', ' SONY AX-53', '', '', '0000-00-00', ' H.264', '0', 'NDIN', '10', 'IDENTES - TESTIMONIANZA DI CAROLINA - ', 'ALTRO', '0');
# INSERT INTO `arch_prof` VALUES ('13809', '0', 'Hard-Disk', '', '0', '1', '0', '3', '2023-08-01', 'LISBONA', ' ALTRO', '', '', '0000-00-00', ' MP4', '0', 'NDDE', '3', 'GMG 2023 LISBONA - NOMADELFIA LOULE INTERVISTE DI TV2000 A MARCO F, NOENI R, SARA G, PIETRO SIENA - GABRIEL', 'ALTRO', '0');
# INSERT INTO `arch_prof` VALUES ('13810', '0', 'Hard-Disk', '', '0', '1', '0', '3', '2023-08-15', 'NOMADELFIA', ' EDIUS', '', '', '0000-00-00', ' MP4', '0', 'NDDI', '3', 'VIDEO ASSUNTA 2023 - VIDEO REALIZZATO DA CARLO E BENEDETTO C, CON DISCORSO DI DON FERDINANDO SULLA STORIA DELLA NOSTRA CHIESA + GIOCHI AL CAMPO SPORTIVO E CENA - LUISA PA, GIANCARLO, ANNA V, MONICA J, CAMILLA U, CHIARA N, CARLO POM, FEDERICO CARM, LORENZO C, PIETRO C, DAVIDE N, VERONICA E, MONIA, MARIASERENA, MANUELA C, MARIALUCE, MARIEJEAN, CHIARA P, SILVIA Z, GERMANA, FRANCESCO N, ADELELMO, ROSELLA A, ANNA S, MIMMO, SEFORA M, PETRA,      ', 'CARLO M', '0');
# INSERT INTO `arch_prof` VALUES ('13811', '0', 'Hard-Disk', '', '0', '1', '0', '5', '2023-08-25', 'LISBONA', ' EDIUS', '', '', '0000-00-00', ' H.264', '0', 'NDDI', '5', 'GMG - DOCUMENTARIO SULLA GMG DI LISBONA 2023 COLLAGE DI FOTO E VIDEO E INTERVISTE  - ELENA Z, DARIO L, DOROTEA S, SAMUEL MA, SAMUELE G, SIMONE A, DIANA F, ELENA F, MARCO F, GIOVANNI A, LUCA A, MATTEO M, NOEMI R, SARA G, ELISA L, SOFIA F, AGNESE A, JOSEF, TARCISIO M, SIMONE L      ', 'ALTRO', '0');
# INSERT INTO `arch_prof` VALUES ('13812', '0', 'Hard-Disk', '', '0', '1', '0', '2', '2023-09-02', 'CECINA', ' EDIUS', '', '', '0000-00-00', ' H.264', '0', 'NDDI', '2', 'NOMADELFIA NEWS 2 SETTEMBRE - FESTA DELL ASSUNTA AL MARE - SERENA A, GIOVANNI Z, KIRIL, DARIO L, JOSEF, LUCA A, GABRIELE Z, DOROTEA S, MARCO F, AGNESE A, MARIAFIORE, SARA MA, GIULIA A, FEDERICO E, DIANA F, ELENA Z, GABRIEL A, MARISA F, TECLA N, MISAELE, BENEDETTO M, NICO, SARA G, MILVA, ELENA F, MARCO O, ELISA F, DAMIANO E, ODETTE, ANGELO A, ZENO S, PAOLO F, MAURICE,    ', 'JOSE J', '0');
# INSERT INTO `arch_prof` VALUES ('13813', '0', 'Hard-Disk', '', '0', '1', '0', '4', '2023-09-07', 'SIENA', ' EDIUS', '', '', '0000-00-00', ' H.264', '0', 'NDDI', '4', 'NEWS 7 SETTEMBRE - CAMMINO - POSTULANTI 2023 - ZENO PA, ANDREA F, STEFANO A, CARLO MO, MONICA C, CAMILLA U, BENEDETTO MA, CRISTINA A, MARIEJEAN, DON GIAMPIETRO, CARLO POM,PETRA, MIMMO, SEFORE M, ', 'CARLO M', '0');
# INSERT INTO `arch_prof` VALUES ('13814', '0', 'Hard-Disk', '', '0', '1', '0', '12', '2023-09-14', 'NOMADELFIA', ' EDIUS', '', '', '0000-00-00', ' H.264', '0', 'NDDI', '12', 'NEWS 14 SETTEMBRE 2023 - ADA SI RACCONTA - ZAIRA, GIORGIA, LORENA G, MINA, MIRELLA M, MARIATERESA, IVAN S, MARICA A, NAZZARENA R, ELIS PA, MARISA F, P. ELIGIO, PAPA FRANCESCO, IRENE,   ', 'NICO', '0');
# INSERT INTO `arch_prof` VALUES ('13815', '0', 'Hard-Disk', '', '0', '1', '0', '6', '2023-09-20', 'NOMADELFIA', ' EDIUS', '', '', '0000-00-00', ' H.264', '0', 'NDDI', '6', 'NEWS 20 SETTEMBRE - ARRIVEDERCI MAMMA ADA - DON FERDINANDO GIULIO C, GLORIA P, GIOSUE B, ZENO S, MONICA C, PETRA, PATRIZIA A, PAOLA A, TIZIANA F, MILVA, ANTONELLA A, EMANUELE DAVOLI, LUCIANA DAVOLI, LUCIANO A, ANGELA SECCIA, CARD ZUPPI, ROSINA VERGARI, MINA, MARIASERENA, MARIO A, PIETRO L, LUISA P, FEDERICO E,    ', 'NICO', '0');
# INSERT INTO `arch_prof` VALUES ('13816', '0', 'Hard-Disk', '', '0', '1', '0', '10', '2023-09-22', 'NOMADELFIA', ' EDIUS', '', '', '0000-00-00', ' MP4', '0', 'NDDI', '10', 'VIDEO ALESSIO ELEONORA - PER ADDIO AL CELIBATO-NUBILATO - ', 'ALTRO', '0');
# INSERT INTO `arch_prof` VALUES ('13817', '0', 'Hard-Disk', '', '0', '1', '0', '11', '2023-09-29', 'NOMADELFIA', ' EDIUS', '', '', '0000-00-00', ' H.264', '0', 'NDDI', '11', 'NEWS 29 SETTEMBRE - CAMBIAMENTO DEI GRUPPI 2023 - BEATRICE M, MARIO A, ANNA NA, NICCOLO, ISAIA, SARA G, MARIO ST, MARIEJEAN, CARLO M, RAFFAELE P, ZENA M, ANDREA F, MONICA C, LUISA PA, FEDERICO E, GABRIEL L, CHIARA L, MANUELA C, ERIC P, FEDERICA P, PAOLO F, SIMONE P, IRENE P, ANDREA S, AGNESE A, MARCO O, DAMIANO E, ZENO S, GABRIELLA, AHARON M, MARCO F, NAZARENA T, NICO, CHIARA N, GABRIELE Z, MICHELA GC, AURORA, SILVIA Z, ALESSANDRO N, DARIO L, ELISA L, MARTA D, GIOSUE, ANTONINE, MATTEO O, MARIAFIORE, ISMAELE, ABIGAIL, SAMUELE CH, STEFANO A, ANNA VE, ADOMAS, LUCA A, PIETRO C, ANNARITA G, GIOIA, TERESA M, MATTIA G, SANDRO S, MICHELE MA, ALESSIO S, LUCA A ELENA L, LIVIO, ANDREA M, GIUDITTA S, PIERANNA, FIORELLA, GIOSUE, MARCELLA, ANNAROSA, ROSELLA A, MIRELLA, FRANCESCO CHECCO, SAMUEL M, GIOELE M, ANDREA F,  DANIELE N, GIULIO R,  ZUELE, NOEMI R, LINO, MORENA, DONATA L, ELIA V, STEFAN L, DAMIANO L, BENEDETTO L, SIMONE L,  STEFANO Z, NICHOLLE M, DANIELE S, GIONATA, MISAELE G, ISABEL G, SONIA G, DOMENICO, TOMMASO N, ANGELA MA, AMOS P, DONATELLA S, MANUEL Z, RAFFAELE S, SUSANNA R, LUCA N, ELISABETTA G, DAVIDE G, EUGENIO R, GIORDANA A, JOSE, DILETTA, ASIA S, ALESSANDRO VA, SARA M, SAMUEL M,  ENRICO M, NOEMI R, MARCO F, ELENA F, DIANA, MARISA F,  NANI, LICE, PAOLO FERRETTI, RICCARDO SP, LIVIO L, NICHOL, CAMILLA M, GIUSEPPE GL, ADELELMO, MAURIZIO C,  ADOMAS, MINA', 'NICO', '0');
# INSERT INTO `arch_prof` VALUES ('13818', '0', 'Hard-Disk', '', '0', '1', '0', '100', '2023-08-16', 'CECINA', ' SONY FS5-K', '', '', '0000-00-00', ' MXF', '0', 'NSSE', '100', 'SERATA A CECINA - SERATA - MARISA F, DAMIANO L, MARCO F, DOROTEA, GABRIELE Z, DIANA F, ELIA V, BENEDETTO M, ARIS, ISAIA, ASIA, FRANCESCA G, GLORIA P, BENEDETTO L, NICOLAS, SARA M, SARA G, SAMUELE G, JOSEF, MARIA FIORE, ENRICO M, FRANCESCO Z, MISAELE, MAURICE, EMANUELE, MELISA, GABRIELE L, ZENO S, MANUEL Z, MARCO O, ', 'NICO', '0');
# INSERT INTO `arch_prof` VALUES ('13819', '0', 'Hard-Disk', '', '0', '1', '0', '1', '2023-08-19', 'COLLESALVETTI', 'CANON G7X', '', '', '0000-00-00', ' MP4', '0', 'NSSE', '1', 'SERATA A COLLESALVETTI - SERATA - GLORIA P, TARCISIO, SAMUELE CH, DEMETRIO, SAMUELE G, DIANA F, NATAN, DILETTA, GABRIEL A, LUCA A, MARCO F, NOEMI', 'DAMIANO', '0');
# INSERT INTO `arch_prof` VALUES ('13821', '0', 'Hard-Disk', '', '0', '1', '0', '3', '2023-08-20', 'LIVORNO', 'CANON G7X', '', '', '0000-00-00', ' MP4', '0', 'NSSE', '3', 'SMONTAGGIO CAMPEGGIO - SMONTAGGIO - ALESSANDRO V, TARCISIO M, LUCA V, ANGELO A, SIMONE L, ISAIA, ELISA L, ZENO S, GIONATA S, CARLO S, ', 'NICO', '0');
# INSERT INTO `arch_prof` VALUES ('13822', '0', 'Hard-Disk', '', '0', '1', '0', '38', '2023-08-31', 'SIENA', ' PAN LX100', '', '', '0000-00-00', ' MP4', '0', 'NREC', '38', 'CAMMINO - POSTULANTI E GIOVANI IN RICERCA - STEFANO A, ZENO PA,DON GIAMPETRO, BENEDETTO M, MARIE JEAN, CARLO POM, MONICA CA, CRISTINA A, CAMILLA, GIANCARLO, BENEDETTO CM, SEFORA M, ANDREA F, GIUSEPPE PICERNO, MIMO S, ', 'STEFANO A', '0');
# INSERT INTO `arch_prof` VALUES ('13823', '0', 'Hard-Disk', '', '0', '1', '0', '9', '2023-09-22', 'NOMADELFIA', ' EDIUS', '', '', '0000-00-00', ' MP4', '0', 'NDDI', '9', 'VIDEO ELEONORA ALESSIO - MATRIMONIO - ELEONORA, ALESSIO, SIDONEA, MARIO A, BENDETTO M, EMMANUELE M, ZENO F, ILARIA M, DANIEL S, MATTIA S', 'TARCISIO M', '0');
# INSERT INTO `arch_prof` VALUES ('13824', '0', 'Hard-Disk', '', '0', '1', '0', '7', '2023-09-26', 'NOMADELFIA', ' EDIUS', '', '', '0000-00-00', ' MP4', '0', 'NDDI', '7', 'CAMBIAMENTO GRUPPI - HIGHLIGHTS 2020 - ', 'ALTRO', '0');
# INSERT INTO `arch_prof` VALUES ('13825', '0', 'Hard-Disk', '', '0', '1', '0', '3', '2023-10-07', 'NOMADELFIA', ' EDIUS', '', '', '0000-00-00', ' MP4', '0', 'NDDI', '3', 'NEWS 7 OTTOBRE - ADDIO ZOE - MESSA FUNERALE SALA DON ZENO - MIMMO, SEFORA, MARISA F, MARIA CM, BENEDETTO C, DILETTA, DON NICOLA, GIONATA, ', 'NICO', '0');
# INSERT INTO `arch_prof` VALUES ('13826', '0', 'Hard-Disk', '', '0', '1', '0', '3', '2023-10-14', 'NOMADELFIA SALA DON ZENO', ' EDIUS', '', '', '0000-00-00', ' MP4', '0', 'NDDI', '3', 'NEWS 14 OTTOBRE - SALA DON ZENO - CARITAS INTERVISTA MONACO CYRIL, SISTEMAZIONE DIGA, LAVORO OLIVE,  - CYRIL, VESCOVO GIOVANNI RONCARI', 'JOSE J - NICO', '0');
# INSERT INTO `arch_prof` VALUES ('13827', '0', 'Hard-Disk', '', '0', '1', '0', '3', '2023-10-21', 'NOMADELFIA', ' EDIUS', '', '', '0000-00-00', ' MP4', '0', 'NDDI', '3', 'NEWS 21 OTTOBRE - CRISTINA DON ERMILLE - MESSA E FUNERALE - DON ERMILLE, CRISTINA D, TATIEN, SONIA G, LUISA PA, MONICA CA, ADA, ANNA V', 'NICO', '0');
# INSERT INTO `arch_prof` VALUES ('13828', '0', 'Hard-Disk', '', '0', '1', '0', '3', '2023-10-28', 'NOMADELFIA', ' EDIUS', '', '', '0000-00-00', ' MP4', '0', 'NDDI', '3', 'NEWS 28 OTTOBRE - INCENDIO AZIENDA IDRAULICA, GIORNATA DIOCESANA DELLE FAMIGLIE - VIGILI DEL FUOCO GROSSETO - FEDERICO E, GIANCARLO, DANIELE S, ZENO S, TONINO CANTELMI, DON NICOLA, SEFORA, ANDREA F, ', 'GIOVANNI R - JOSE J - NICO', '0');
# INSERT INTO `arch_prof` VALUES ('13829', '0', 'Hard-Disk', '', '0', '1', '0', '6', '2023-11-04', 'NOMADELFIA', ' EDIUS', '', '', '0000-00-00', ' MP4', '0', 'NDDI', '6', 'NEWS 04 NOVEMBRE - MATRIMONIO - ANDREA MARIA GRAZIA - FEDERICO E, DAVIDE N, LORENZO C, ELENA F, CHIRARA L, SOFIA F, MICHAEL, IOLE, ANDREA M, GIOSUE, CHRISTELLA, MARICA, DILETTA, MARISA, DAMIANO L', 'NICO - JOSE J - ALTRO', '0');
# INSERT INTO `arch_prof` VALUES ('13830', '0', 'Hard-Disk', '', '0', '1', '0', '22', '2023-11-07', 'GROSSETO CANALE TV9', ' ALTRO', '', '', '0000-00-00', ' MP4', '0', 'NDDE', '22', 'I NOSTRI GIORNI - GIORNATA DELLE FAMIGLIE E CAMINO SINODALE - SERVIZIO TV GIACOMO D ONOFRIO, TONINO CANTELMI, DON PAOLO GENTILI', 'ALTRO - JOSE J', '0');
# INSERT INTO `arch_prof` VALUES ('13831', '0', 'Hard-Disk', '', '0', '1', '0', '3', '2023-11-11', 'NOMADELFIA, AEROPORTO FIUMICINO', ' EDIUS', '', '', '0000-00-00', ' MP4', '0', 'NDDI', '3', 'NEWS 11 NOVEMBRE - PARTENZA PER LA TANZANIA BATTESIMI - INTERVISTE, MESSA - SAMUELE CH, DOROTEA, MARISA , DANIELE S, FEDERICO E, LIAM M, GIACOMO R, EDOARDO ', 'NICO - JOSE J - ALTRO', '0');
# INSERT INTO `arch_prof` VALUES ('13832', '0', 'Hard-Disk', '', '0', '1', '0', '4', '2023-11-18', 'NOMADELFIA ROMA', ' EDIUS', '', '', '0000-00-00', ' MP4', '0', 'NDDI', '4', 'NEWS 18 NOVEMBRE - FAMIGLIE A ROMA - INTERVISTE, CONDIVISIONE COMUNITA DELLA CASA, LE BISSARRE E DELLA TRINITA - GIANCARLO, DON FERDINANDO, MARCO O, DON VIRGINIO', 'NICO - ALTRO', '0');
# INSERT INTO `arch_prof` VALUES ('13833', '0', 'Hard-Disk', '', '0', '1', '0', '3', '2023-11-20', 'NOMADELFIA', ' EDIUS', '', '', '0000-00-00', ' MP4', '0', 'NDDI', '3', 'VIDEO I DIRITTI DEI BAMBINI - SCUOLA MEDIA - ELISABETTA, ENRICO, DEMETRIO, ISACCO, DENISA, NICOLAS, GABRIELE, DONATA', 'JOSE J', '0');
# INSERT INTO `arch_prof` VALUES ('13834', '0', 'Hard-Disk', '', '0', '1', '0', '3', '2023-09-07', 'NOMADELFIA GRUPPO ASSUNTA', ' CELLULARE', '', '', '0000-00-00', ' MP4', '0', 'NRLA', '3', 'SMONTAGGIO CAVI TV E TELEFONO - PULIZIA AMBENTI - NICO', 'JOSE J - ALTRO', '0');
# INSERT INTO `arch_prof` VALUES ('13835', '0', 'Hard-Disk', '', '0', '1', '0', '30', '2023-09-08', 'MOSCONA, GRUPPO ROSELLANA', ' SONY AX-53 DJI POCKET 2', '', '', '0000-00-00', ' MP4', '0', 'NRGE', '30', 'CARLINO MOSCONA, SUONA SAX - MILVA, CARLINO, NICO, LUISA DEL VALLE, FEDERICO E', 'NICO - ALTRO', '0');
# INSERT INTO `arch_prof` VALUES ('13836', '0', 'Hard-Disk', '', '0', '1', '0', '30', '2023-09-12', 'NOMADELFIA, SALA DON ZENO', ' SONY AX-53 SONY FS5-K', '', '', '0000-00-00', ' MP4', '0', 'NRCE', '30', 'FUNERALE ADA - MESSA, BALLO MESSICANO  - MARIO A, STEFANO A, GIORNATA, RAFFAELE S, ZENO S, DAMIANO, ELENA F, AHARON M, VERONICA E, ANNAROSA, FEDERICO E, ZAIRA, NICO, DON FERDINANDO, GUGLIELMO, PIETRO C, PAOLA ADA, MAURICE, DAVIDE G', 'NICO - DAMIANO - ALTRO', '0');
# INSERT INTO `arch_prof` VALUES ('13837', '0', 'Hard-Disk', '', '0', '1', '0', '14', '2023-09-14', 'NOMADELFIA, VIGNA', ' SONY AX-53 DRONE DJI MINI 2', '', '', '0000-00-00', ' MP4', '0', 'NRLA', '14', 'VENDEMMIA - VIGNA UVA BIANCA - DAVIDE G, CARLO POM, SANDRO D, SAMUELE M, MAURICE, DONATELLA, MELISA, ANTONIE, MARCO O, GABRIELE Z, LUCA R, MATTIA G, LUCA A, DAMIANO, ENRICO M', 'NICO - ALTRO', '0');
# INSERT INTO `arch_prof` VALUES ('13838', '0', 'Hard-Disk', '', '0', '1', '0', '155', '2023-09-18', 'NOMADELFIA', ' SONY AX-53 DRONE DJI MINI 2 GOPRO DJI POCKET 2', '', '', '0000-00-00', ' MP4', '0', 'NRGR', '155', 'CAMBIAMENTO GRUPPI - GIRO DEI GRUPPI - LUCA A, ALESSANDRO V, GIONATA, DILETTA, ROBERTO N, ENRICO GENOVESI, ALI, SABRINA S, MANUELA, SAMUELE CH, ELISABETTA G, LINO E, GIUSEPPE G, LETIZIA G, GIOVANNI A, MELISA, SARA M, ALESSIO S, ELENA L, TOMMASO N, ANTONIE, NAZARENA T, STEFANO A, FRANCA, MARCELLA, JOSEF, GIUSTO, ABIGAIL, ISMAELE, SERENA A, IOLE, LUISA PA, ZENA M, AHARON, ALESSANDRO N, SONIA G, ANDREA F, DAVIDE P, IRENE P, PIETRO M, ANDREA M, FEDERICO E, ZENO S, GIANCARLO, MARIA GRAZIA, LUISA S, CHANTAL, LORENZO C, GABRIEL L, MISALE, ISABEL, MATTIA B, SUSANNA R, DANIELE S, MARIA FIORE, IRENEO, GIORDANO, GLORIA P, RAFFAELE P, AURORA, LETIZIA S, ANNA V, ADOMAS, GIOIA, CHECCO, ODETTE, MARCO O, ASIA, GIOVANNI R, MARCO F, ONORATO, LIVIO, MARI JEAN, GABRIELLA, BEATRICE F, ANGELO, DON FERDINANDO, DANIELE PA, GIOELE M, DARIO L, BENEDETTO L, SIMONE L, DAMIANO L, ANTONELLO, MARIETTO, MICHELE M, CRISTINA A, RACHELE, GIOSUE, MANUEL Z, NICO, MARIO A, MAURIZIO CA, NICOLE, TARCISIO, MARIA BEATRICE, NICOLO M, MAURIZIO C, MARIA M, ELIA V, DANIELE S, LICE, DOROTEA, ANNARITA, MARIA LUCE, CRISTIANA S, JOY, NICOLAS, JOSEF, STEFANO GIUSEPPE Z,  ROSELLA, GABRIEL, MICHELA, MINA, GIULIA A, MARIA SERENA, SIMONE P, GIGI, SILVIA Z, ELENA Z, ANTONIETTA G, MORENA, GERMANA, CARLO MO, PIETRO C, RACHELLE, FIORELLA, MIRIO', 'NICO - ALTRO', '0');
# INSERT INTO `arch_prof` VALUES ('13839', '0', 'Hard-Disk', '', '0', '1', '0', '15', '2023-09-21', 'NOMADELFIA', ' SONY FS5-K ALTRO', '', '', '0000-00-00', ' MP4', '0', 'NRCE', '15', 'MESSA INZIO SCUOLA - INIZIO SCUOLA - DON FERDINANDO, ALUNNI SCUOLA, FOTO TUTTA LA SCUOLA, TOMMASO N', 'NICO - ALTRO', '0');
# INSERT INTO `arch_prof` VALUES ('13840', '0', 'Hard-Disk', '', '0', '1', '0', '28', '2023-09-27', 'NOMADELFIA', ' SONY FS5-K ALTRO', '', '', '0000-00-00', ' MTS MXF', '0', 'NRGR', '28', 'INTERVISTA AL MONACO CYRIL ZUM - GRUPPO CENACOLO, SCUOLA, METALPLASTICA - CHIARA L, ANTONIETA G, CHANTAL S, MORENA, ADOMAS, JOSEF, MINA, AZZURRA, GIANCARLO, DOROTEA, SILVIA S, GIOVANNI R, GERMANA, MARISA F, AZZURRA', 'NICO - ALTRO', '0');
# INSERT INTO `arch_prof` VALUES ('13841', '0', 'Hard-Disk', '', '0', '1', '0', '9', '2023-09-28', 'NOMADELFIA', ' SONY AX-53 ALTRO', '', '', '0000-00-00', ' MP4 MXF', '0', 'NRLA', '9', 'VENDEMMIA - VIGNETTO POGGETTO - SIMONE A, DONATA, FRANCESCA G, DENISA, STEFANO A, RAFFAELE S, RENATO, ELENA F, MATTIA G, NICO, ALI, EUGENIO, CRISTINA A, MELISA, GIANCARLO, MANUEL Z, ALESSANDRO V, GIOVANNI Z, ZENO S, CAMILLA URBINO, SERENA A, MICHELE M, MARIA A', 'MARCO F - ALTRO', '0');
# INSERT INTO `arch_prof` VALUES ('13842', '0', 'Hard-Disk', '', '0', '1', '0', '64', '2023-09-29', 'NOMADELFIA', ' SONY AX-53 DRONE DJI MINI 2 ALTRO', '', '', '0000-00-00', ' MP4 MXF', '0', 'NRCE', '64', 'MESSA FUNERALE ZOE - SALA DON ZENO - MONICA CA, ANNAROSA, SEFORA, IRENE P, STEFANO Z, PAOLO F, MARIO A, GIOVANNI A, ALESSANDRO V, DANIELE S, MIMMO, MARIA CM, CHELIDONIA, SABRINA S, VERONICA E, BENEDETTO C, DAMIANO E, MARISA F, ISACCO P, FRANCESCO Z, FEDERICO EV, AMOS, DILETTA, RAFFAELE P, EMANUELE Z, MARIA LUCE, TERESA, DON FERDINANDO, GLORIA P', 'NICO - DAMIANO - ALTRO', '0');
# INSERT INTO `arch_prof` VALUES ('13843', '0', 'Hard-Disk', '', '0', '1', '0', '2', '2023-09-29', 'GRUPPO GIOVANNI PAOLO II', ' SONY AX-53 DRONE DJI MINI 2 ALTRO', '', '', '0000-00-00', ' MP4', '0', 'NRGR', '2', 'VARIE ROMA - MESSA - FRANCESCO A, CAROLINA, PAOLO E', 'ALTRO', '0');
# INSERT INTO `arch_prof` VALUES ('13844', '0', 'Hard-Disk', '', '0', '1', '0', '4', '2023-10-07', 'NOMADELFIA', ' SONY AX-53 DRONE DJI MINI 2 ALTRO', '', '', '0000-00-00', ' MP4', '0', 'NRGE', '4', 'CONV CARITAS - SALA DON ZENO - VESCOVO GIOVANNI RONCARI', 'JOSE J', '0');
# INSERT INTO `arch_prof` VALUES ('13845', '0', 'Hard-Disk', '', '0', '1', '0', '12', '2023-10-09', 'NOMADELFIA', ' SONY AX-53 DRONE DJI MINI 2 ALTRO', '', '', '0000-00-00', ' MP4', '0', 'NRIN', '12', 'TESTIM ZENO F - SALA DON ZENO - GIANCARLO A, SILVIA Z, RACHELLE, DON NICOLA, ZENO S, DON GIAMPIETRO, DON  FERDINANDO, PAOLO F, GIULIA, FEDERIA P', 'NICO', '0');
# INSERT INTO `arch_prof` VALUES ('13846', '0', 'Hard-Disk', '', '0', '1', '0', '6', '2023-10-11', 'NOMADELFIA', ' SONY AX-53 DRONE DJI MINI 2 ALTRO', '', '', '0000-00-00', ' MXF MP4', '0', 'NRLA', '6', 'DIGA E OLIVE - LAVORO ALLA DIGA, OLIVE, FRANTOIO - PIETRO C, ZENO F, LINO E, FEDERICO E, ALESSANDRO N, STEFANO A, MATTIA G, CHECCO, CHIARA N, SAMUELE C', 'NICO', '0');
# INSERT INTO `arch_prof` VALUES ('13847', '0', 'Hard-Disk', '', '0', '1', '0', '2', '2023-10-13', 'NOMADELFIA', ' SONY AX-53 DRONE DJI MINI 2 ALTRO', '', '', '0000-00-00', ' MXF MP4', '0', 'NRLA', '2', 'TAGLI DEI PALI BETLEM - ELETTRICISTI, EDILIZIA - MARCO F, DANIELE PA, SAMUELE C, SAMUELE CH', 'NICO', '0');
# INSERT INTO `arch_prof` VALUES ('13848', '0', 'Hard-Disk', '', '0', '1', '0', '31', '2023-10-13', 'NOMADELFIA', ' SONY FS5-K DRONE DJI MINI 2 CELLULARE ALTRO', '', '', '0000-00-00', ' MXF MP4 MOV', '0', 'NRGE', '31', 'INCENDIO AZIENDA IDRAULICA - LAVORI, VIGILI DEL FUOCO GROSSETTO - SILVIA D, MONICA J, GIANCARLO, SAMUELE C, GABRIELE L, DANIELE S, RAFFAELE S, MANUEL Z, PIETRO C, ZENO S', 'JOSE J - GIOVANNI R - NICO', '0');
# INSERT INTO `arch_prof` VALUES ('13849', '0', 'Hard-Disk', '', '0', '1', '0', '110', '2023-10-15', 'NOMADELFIA', ' SONY AX-53 SONY FS5-K DJI POCKET 2 ALTRO', '', '', '0000-00-00', ' MP4 MXF', '0', 'NRCE', '110', 'INCONTRO CANTELMI E MESSA VESCOVO - SALA DON ZENO - GIOVANNI A, LORENZO C, MILVA, CRISTIANA S, VALENTINA A, ELISA L, ELENA F, NATALIA S, VESCOVO GIOVANNI RONCRI, NAZARENA R, MARISA F, RACHELLE, JOSEF, NOEMI, PAOLO, DON NICOLA, AGNESE A, CHIARA N, ENRICO FOTO, TONINO CANTELMI, DON PAOLO', 'NICO - ALTRO', '0');
# INSERT INTO `arch_prof` VALUES ('13850', '0', 'Hard-Disk', '', '0', '1', '0', '29', '2023-10-19', 'NOMADELFIA', ' SONY AX-53', '', '', '0000-00-00', ' MP4 MXF', '0', 'NRCE', '29', 'FUNERALE CRISTINA - SALA DON ZENO - DON FERDINANDO, SAMUELE G, MARISA F, DIANA F, GIOVANNI Z, TARCISIO M, GIANNI S, ZENO S, STEFANO A, RAFFAELE S, ZENO F', 'NICO - ALTRO', '0');
# INSERT INTO `arch_prof` VALUES ('13851', '0', 'Hard-Disk', '', '0', '1', '0', '70', '2023-10-21', 'NOMADELFIA', ' SONY FS5-K', '', '', '0000-00-00', ' MP4', '0', 'NRSP', '70', 'CONCERTO GOSPEL - SALA CULTURA - ROBERTO N, DAVIDE P, AMOS, ARIEL', 'NICO', '0');
# INSERT INTO `arch_prof` VALUES ('13852', '0', 'Hard-Disk', '', '0', '1', '0', '260', '2023-10-29', 'NOMADELFIA', ' SONY AX-53 SONY FS5-K DJI POCKET 2 DRONE DJI MINI 2', '', '', '0000-00-00', ' MP4 MXF', '0', 'NRCE', '260', 'MATRIMONIO ANDREA MGRAZIA - SALA DON ZENO - FRANCESCO Z, AHARON, IRENEO, LINO S, DANIELE S, CHRISTELLE, LIDIA, SAMUELE CH, ANDREA M, IRENE S, MARISA F, ELENA Z, NICO, GIOVANNI R, ELIA V, CARLO MO, MARCO G, MIRIAM, LORENZO C, FEDERICO E, ELENA F, AZZURRA, CHIARA L, ABIGAIL, TERESA, MARCO F, LUISA PA, DON NICOLA, LUISA P, GREGORIO, MARCELLA M, LIVIO, STEFANO Z, RAFFAELE P, MARICA, ANNA G, ODETTE, CRISTIANA S, ROBERTO N, MARIA BEATRICE, MARISA, DILETTA, JOSEF, MONICA J  ', 'JOSE J - NICO - ZENO - GIOSUE', '0');
# INSERT INTO `arch_prof` VALUES ('13853', '0', 'Hard-Disk', '', '0', '1', '0', '8', '2023-10-31', 'NOMADELFIA', ' SONY AX-53 SONY FS5-K', '', '', '0000-00-00', ' MP4 MXF', '0', 'NDIN', '8', 'INTERVISTE PARTENTI TANZANIA - PARTENZA - SAMUELE CH, DOROTEA, MARISA , DANIELE S, MARIO A, CHECCO, FEDERICO E', 'NICO', '0');
# INSERT INTO `arch_prof` VALUES ('13854', '0', 'Hard-Disk', '', '0', '1', '0', '26', '2023-10-31', 'NOMADELFIA', ' SONY AX-53', '', '', '0000-00-00', ' MP4', '0', 'NRCE', '26', 'NUOVI MINISTRI DELLA COMUNIONE - MESSA - VESCOVO GIOVANNI RONCARI, NICO, MILVA, GUGLIELMO S, DON FERDINANDO, SILVIA D, ZENO S, PIETRO C, ELENA F, MONICA C, GIOVANNI L, CHIARA L, MARIA P', 'JOSE J', '0');
# INSERT INTO `arch_prof` VALUES ('13855', '0', 'Hard-Disk', '', '0', '1', '0', '7', '2023-10-31', 'NOMADELFIA', ' SONY AX-53', '', '', '0000-00-00', ' MP4', '0', 'NRLA', '7', 'RACCOLTA OLIVE - LAVORO - STEFANO A, GIONATA, DANIELE PA, ZENO F, RAFFAELE S, SAMUELE C, ALESSANDRO N, CHECCO, ANDREA S,LINO E', 'NICO', '0');
# INSERT INTO `arch_prof` VALUES ('13856', '0', 'Hard-Disk', '', '0', '1', '0', '25', '2023-11-01', 'NOMADELFIA', ' SONY AX-53', '', '', '0000-00-00', ' MP4', '0', 'NRCE', '25', 'BATTESIMI LIAM, EDOARDO, GIACOMO - SALA DON ZENO - GUGLIELMO S, JOSE RAMON, DANIELA A, MATTEO L, STELLA D, DON GIAMPIETRO, DOROTEA B, MARIA STELLA, GIONATA, DILETTA, LICE PIETRO L, SEFORA, MIMMO, TOMMASO N, MINA, GIOVANNI R, ONORATO, STEFANO, PIETRO C, REMO RINALDI, MARCO F', 'NICO', '0');
# INSERT INTO `arch_prof` VALUES ('13857', '0', 'Hard-Disk', '', '0', '1', '0', '90', '2023-11-04', 'NOMADELFIA ROMA', ' SONY AX-53 PANASONIC', '', '', '0000-00-00', ' MP4', '0', 'NDIN', '90', 'FAMIGLIE ROMA - INCRONTRO COMUNITA - CONDIVISIONE COMUNITA DELLA CASA, LE BISSARRE E DELLA TRINITA - GIANCARLO, DON FERDINANDO, MARCO O, DON VIRGINIO', 'CARLO M - MARIA BEATRICE', '0');
# INSERT INTO `arch_prof` VALUES ('13859', '0', 'Hard-Disk', '', '0', '1', '0', '15', '2023-11-08', 'MARE', ' SONY AX-53', '', '', '0000-00-00', ' MP4', '0', 'NRSC', '15', 'MEDIE AL MARE - RIPRESE PER VIDEO - ELISABETTA, ENRICO, DEMETRIO, ISACCO, DENISA, NICOLAS, GABRIELE, DONATA', 'CRISTIANA - GIOVANNI L', '0');
# INSERT INTO `arch_prof` VALUES ('13860', '0', 'Hard-Disk', '', '0', '1', '0', '3', '2023-11-08', 'NOMADELFIA', ' DJI POCKET 2', '', '', '0000-00-00', ' MP4', '0', 'NRLA', '3', 'RACOLTA OLIVE DIETRO STALLA - VARIE RIPRESE, ULIVETO SUBIACO - MATTIA, LINO E, SAMUELE C', 'JOSE J', '0');
# INSERT INTO `arch_prof` VALUES ('13861', '0', 'Hard-Disk', '', '0', '1', '0', '12', '2023-11-17', 'NOMADELFIA', ' SONY FS5-K', '', '', '0000-00-00', ' MXF', '0', 'NRLA', '12', 'MESSA RINGRAZIAMENTO RACCOLTO - MESSA 2023 - GUGLIELMO S, PIETRO C, ZENO F, MATTIA G, ALESSANDRO N, MILVA, CRISTINA A, GERMANA, RONERTO N, AURORA, LUISA DEL VALLE, ODETTE, RAFFAELE S, DON FERDINANDO, ROBERTO N, TIZIANO G, GIOVANNI L, DON NICOLA', 'NICO', '0');
# INSERT INTO `arch_prof` VALUES ('13862', '0', 'Hard-Disk', '', '0', '1', '0', '8', '2023-11-05', 'NOMADELFIA', ' SONY AX-53', '', '', '0000-00-00', ' MP4', '0', 'NRGR', '8', 'COMPLEANNO PIERANNA - GRUPPO POGETTO - MARCELLA M, NICOLE, GIOELE M, MILVA, VALENTINA, ENRICO, ALESSANDRO V, ZAIRA, MANUEL Z, AHARON, TERESA, ', 'NICO', '0');
# INSERT INTO `arch_prof` VALUES ('13863', '0', 'Hard-Disk', '', '0', '1', '0', '24', '2023-08-18', 'CECINA', ' SONY AX-53', '', '', '0000-00-00', ' MP4', '0', 'NSSE', '24', 'FESTA FINE APOSTOLATO - CAMPEGGIO - AMOS, GLORIA, FEDERICO E, NICO, RACHELLE, JOSEF, DIANA, ERIK, IRENE P, MAURICE, MICHELE M, ROBERTO N, SAMUELE CH, GIOVANNI A, MARCO F, EUGENIO, SAMUELE M, ODETTE, MILVA, ELISA L, SERENA A, SAMUELE G, ELENA Z, SIMONE A, DAMIANO L, DOROTEA, DANIELE N, STELLA G', 'DAVIDE G', '0');
# INSERT INTO `arch_prof` VALUES ('13864', '0', 'Hard-Disk', '', '0', '1', '0', '3', '2023-08-03', 'LISBONA', ' ALTRO', '', '', '0000-00-00', ' MP4', '0', 'NRVG', '3', 'GMG 2023, DA NOMADELFIA (GROSSETO) IN PORTOGALLO I GIOVANI IN VIAGGIO VERONICA E - TV DI PORTOGALLO - VERONICA E, DIANA, MARCO F, SARA G, NOEMI, GABRIEL', 'ALTRO', '0');
# INSERT INTO `arch_prof` VALUES ('13865', '0', 'Hard-Disk', '', '0', '1', '0', '3', '2023-11-25', 'NOMADELFIA', ' EDIUS', '', '', '0000-00-00', ' MP4', '0', 'NDDI', '3', 'MESSA RINGRAZIAMENTO OLIO, VINO - FESTA AGRARIA, ROSELLANA, PANORAMICHE DRONE - GIANCARLO, DON FERDINANDO, GIOVANNI L, TIZIANO G, RAFFAELE S, ALESSANDRO N, MILVA, CRISTIANA S, VALENTINA A, AURORA, MICHELA, FEDERICO E, ZENO F, STEFANO A, DANIELE N, CHIARA N, MARIO A', 'NICO', '0');
# INSERT INTO `arch_prof` VALUES ('13866', '0', 'Hard-Disk', '', '0', '1', '0', '17', '2023-11-16', 'NOMADELFIA', ' SONY FS5-K', '', '', '0000-00-00', ' MXF', '0', 'NRCU', '17', 'PADRE DAMINANO SALUTO PADRE LAURENCE - AGGIORNAMENTO SITUAZIONE LIBANO, SALUTI TANZANIA - GIANCARLO, PADRE DAMIANO, PADRE LAURENCE, DON FERDINANDO', 'JOSE J', '0');
# INSERT INTO `arch_prof` VALUES ('13867', '0', 'Hard-Disk', '', '0', '1', '0', '15', '2023-11-15', 'ROMA', ' SONY AX-53', '', '', '0000-00-00', ' MP4', '0', 'NRVG', '15', 'ELEMENTARI A ROMA - VISITA SCUOLA - SILVIA D, FRANCESCO ANT, FRANCESCO Z, MONICA CA, CHIARA L, GIOELE M, SILVIA Z, GLORIA P, GIULIO, DON VIRGINIO, ARIEL, IRENE P, MARIE JEAN, PADRE LAWRENCE, FEDERICO EV, LINO E, NOEMI', 'BEATRICE M, CARLO MO', '0');
# INSERT INTO `arch_prof` VALUES ('13868', '0', 'Hard-Disk', '', '0', '1', '0', '80', '2023-11-26', 'ROMA', ' SONY AX-53', '', '', '0000-00-00', ' MP4', '0', 'NRVG', '80', 'SUPERIORE ROMA - VISITA SCUOLA - LINO E, MARIE JEAN, ROSELLA, AMTONELLA F, BEATRICE F, VALENTINA A, LETIZIA S, MELISA, MAURICE, ANTONELLA F, MATTEO M, ERICK, VALENTINA A, ATTRICE BEATRICE BAZI, CAPITANO ULTIMO, DAVIDE G, ZENO S, DIANA F, ', 'SAMUELE G, ZENO S, CARLO MO', '0');
# INSERT INTO `arch_prof` VALUES ('13869', '0', 'Hard-Disk', '', '0', '1', '0', '3', '2023-11-26', 'TANZANIA', ' PREMIERE', '', '', '0000-00-00', ' MP4', '0', 'NDDE', '3', 'NOVEMBRE 2023 - RIPRESE NOVEMBRE, LAVORI, ORTO, GRUPPO FAMIGLIARE, CAVI - MARIO A, BENEDETTO, SAMUELE CH, MARISA, DOROTEA, LAVORATORI TANZANIA, DANIELE S, ANGELA M, FEDERICO E, ', 'BENEDETTO M', '0');
# INSERT INTO `arch_prof` VALUES ('13870', '0', 'Hard-Disk', '', '0', '1', '0', '3', '2023-12-02', 'TANZANIA', ' EDIUS', '', '', '0000-00-00', ' MP4', '0', 'NDDI', '3', 'NEWS 2 DICEMBRE 2023 - RIPRESE NOVEMBRE, LAVORI, ORTO, GRUPPO FAMIGLIARE, CAVI - MARIO A, BENEDETTO, SAMUELE CH, MARISA, DOROTEA, LAVORATORI TANZANIA, DANIELE S, ANGELA M, FEDERICO E, ', 'BENEDETTO M', '0');
# INSERT INTO `arch_prof` VALUES ('13871', '0', 'Hard-Disk', '', '0', '1', '0', '4', '2023-07-19', 'MONTERONI D ARBIA', ' EDIUS', '', '', '0000-00-00', ' MP4', '0', 'NSSE', '4', 'NEWS 19 LUGLIO - SERATA - SINDACO GABRIELE BERNI, MILVA, FRANCESCO Z, NICO, IRENE, MARIA, EMANUELE Z, TECLA, MELISA M, MAURICE, DANIELE N', 'NICO', '0');
# INSERT INTO `arch_prof` VALUES ('13872', '0', 'Hard-Disk', '', '0', '1', '0', '43', '2023-12-02', 'NOMADELFIA', ' SONY AX-53 SONY FS5-K', '', '', '0000-00-00', ' MP4 MXF', '0', 'NRCE', '43', 'BATTESIMI - ANASTASIA, MARIA P, NICOLO, DOROTEA R SALA DON ZENO - MARTHA, ADOMAS, DAMIANO L, STEFAN, GIOVANNI Z, ERICK, PIETRO C, RAFFAELE S, SUSANNA R, DON NICOLA, MATTIA B, MARIA BEATRICE, SARA M, LETIZIA G, MIMMO, MONICA CA, MANUEL Z, ZENA M, CHIARA P, GLORIA, GIOVANNI L, GUGLIELMO, GIUSEPPE G, SEFORA, ZENO F, RACHELE, ESTER P, DON FERDINANDO ', 'NICO - ZENO', '0');
# INSERT INTO `arch_prof` VALUES ('13873', '0', 'Hard-Disk', '', '0', '1', '0', '36', '2023-12-13', 'NOMADELFIA', ' SONY AX-53 SONY FS5-K', '', '', '0000-00-00', ' MP4', '0', 'NRSC', '36', 'RIPRESE 1 MEDIA VIDEO I TRE DONI - GRUPPI, BRUCIATA, ROSELLANA, CIMITERO, DIGA - DEMETRIO, DENISA, ELISABETTA, RON, DONATA, ISACCO P, ENRICO, NICOLAS, GABRIELE P', 'JOSE J', '0');
# INSERT INTO `arch_prof` VALUES ('13875', '0', 'Hard-Disk', '', '0', '1', '0', '3', '2023-12-09', 'NOMADELFIA', ' EDIUS', '', '', '0000-00-00', ' MP4', '0', 'NDDI', '3', 'NEWS 9 DIC 2023 BATTESIMI - SALA DON ZENO - ANASTASIA, MARIA P, NICOLO, DOROTEA R SALA DON ZENO - MARTHA, ADOMAS, DAMIANO L, STEFAN, GIOVANNI Z, ERICK, PIETRO C, RAFFAELE S, SUSANNA R, DON NICOLA, MATTIA B, MARIA BEATRICE, SARA M, LETIZIA G, MIMMO, MONICA CA, MANUEL Z, ZENA M, CHIARA P, GLORIA, GIOVANNI L', 'NICO', '0');
# INSERT INTO `arch_prof` VALUES ('13876', '0', 'Hard-Disk', '', '0', '1', '0', '9', '2023-07-14', 'CASTELLINA SCALO SI', ' EDIUS', '', '', '0000-00-00', ' H.264', '0', 'NDDI', '9', 'NEWS 14 LUGLIO - MONTAGGIO CAMPEGGIO, SERATA SINDACO ANDREA FROSINI, VISITA A MONTERIGGIONI, E BAGNO AL PARCO FLUVIALE DELL ELSA - ', 'NICO', '0');
# INSERT INTO `arch_prof` VALUES ('13877', '0', 'Hard-Disk', '', '0', '1', '0', '18', '2023-12-20', 'NOMADELFIA', ' SONY AX-53 DRONE DJI MINI 4', '', '', '0000-00-00', ' MP4', '0', 'NRSP', '18', 'DRONE CALCIO TRAMONTO PANORAMICHE - CAMPO SPORTIVO - JOY, SAMUEL M, CROCE, BAR, SCUOLA, METALPLASTICA, TRAMONTO, BRUCIATA, VIGNA, SUGHERA', 'NICO', '0');
# INSERT INTO `arch_prof` VALUES ('13878', '0', 'Hard-Disk', '', '0', '1', '0', '3', '2023-12-24', 'NOMADELFIA', ' SONY AX-53', '', '', '0000-00-00', ' MP4', '0', 'NRGE', '3', 'VARIE BAR SALA DON ZENO - VARIE - EMANUELE Z, NANNI, NAZARENA T, DAMIANO L, SAMUELE CH, ZENO F, ANDREA F, ALESSANDRO N, ERIC P, GIOVANNI Z, MATTEO M, CAMILLLA, ZENO S, DIANA F', 'NICO', '0');
# INSERT INTO `arch_prof` VALUES ('13879', '0', 'Hard-Disk', '', '0', '1', '0', '32', '2023-12-25', 'NOMADEFIA SALA DONZENO', ' SONY AX-53 SONY FS5-K', '', '', '0000-00-00', ' MP4 MXF', '0', 'NRCE', '32', 'NATALE PRESEPE VIVENTE - MESSA - MARIA PC, MAURIZIO C, GIOVANNI L, AGNESE S, LIBERO, LUISA P, PIETRO L, ZAIRA, GIOLE M, ', 'NICO', '0');
# INSERT INTO `arch_prof` VALUES ('13881', '0', 'Hard-Disk', '', '0', '1', '0', '120', '2023-12-26', 'NOMADELFIA', ' SONY FS5-K SONY AX-53', '', '', '0000-00-00', ' MXF MP4', '0', 'NRGE', '120', 'CONCERTO - NATALE - ROBERTO N, ENRICO M, ELISABETTA, DENISA, DONATA L, DILETTA, GAIA, NICOLAS, DAVIDE G, BEATRICE F, SILVIA D, LUISA PA, MARIA FIORE, ANNA N', 'NICO', '0');
# INSERT INTO `arch_prof` VALUES ('13882', '0', 'Hard-Disk', '', '0', '1', '0', '11', '2023-12-31', 'NOMADELFIA', ' SONY AX-53 DRONE DJI MINI 4', '', '', '0000-00-00', ' MP4', '0', 'NRSP', '11', 'CALCIO, PANORAMICHE - CAMPO SPORTIVO - ISAIA, DAVIDE A, FEDERICO E', 'NICO', '0');
# INSERT INTO `arch_prof` VALUES ('13883', '0', 'Hard-Disk', '', '0', '1', '0', '300', '2023-12-31', 'NOMADELFIA', ' SONY AX-53 SONY FS5-K BLACKMAGIC VIDEO ASSIST', '', '', '0000-00-00', ' MP4 MXF MOV', '0', 'NRFE', '300', 'FESTA CAPODANNO - RETTANGOLONE - GIULIA A, TARCISIO M, GIOVANNI A, ANNA G, ELISA L, LINO E, MAURIZIO C, SAMUELE G, SIMONE L, SAMUEL A, AGNESE S, CHECCO, LETIZIA G, PIETRO M, SARA G, DAVIDE G, GIUSEPPE G, DONATA, STEFAN L, GABRIELLA, MATTIA G, LUISA P, PIETRO L, CARLO POM, FEDERICO E, MIRIAM F, ANDREA F, DIANA F, MANUEL Z, TAMARA B, JOSEF, RACHELLE, DARIO L, ROBERTO N, RAFFAELE P, ELIA V, DANIELE PA, LUCA CRI, CHRISTELLE, MARIA FIORE, MARCO O, MAURICE, ERIC, GABRIEL A, SIMONE A, SAMUEL M, DILETTA, NOEMI, BEATRICE F, GIOVANNI Z, MARIA Z, GREGORIO, ROSY, MATTEO M, DON NICOLA, DON GIAMPIETRO, MARICA, LIDIA, LETIZIA S, LICE, ABIGAIL, ASIA, FRANCA, MELISA, STEFANO A, ODETTE, GIONATA, MIRIO, SONIA G, ISABEL, NICO, MILVA, VALENTINA A, ALSEEANDRO V, AHARON M, ZENO S, SILVIA Z, GIGI, MARCELA M, MICHELE M, MICHELA, MISALE, SAMUELE C, DANIELE S, CAMILLA\r\n', 'NICO - JOSE J - ALTRO', '0');
# INSERT INTO `arch_prof` VALUES ('13884', '0', 'Hard-Disk', '', '0', '1', '0', '48', '2024-01-01', 'NOMADELFIA', ' SONY AX-53 SONY FS5-K', '', '', '0000-00-00', ' MP4 MXF', '0', 'NRCE', '48', 'MESSA PRIMO ANNO - SALA DON ZENO - ANASTASIA G, MISALE, DON FERDINANDO, ANTONELLO, MARIETTO, STEFANO Z, GLORIA P, TERESA, ABIGAIL, RAFFAELE P, AHARON, NICOLE, PAOLO LUCAS, IRENE P, DON GIAMPIETRO, TOMMASO N', 'NICO - JOSE J', '0');
# INSERT INTO `arch_prof` VALUES ('13885', '0', 'Hard-Disk', '', '0', '1', '0', '38', '2024-01-06', 'NOMADELFIA', ' SONY AX-53 SONY FS5-K', '', '', '0000-00-00', ' MP4 MXF', '0', 'NRCE', '38', 'MESSA EPIFANIA - SALA DON ZENO - ANTONIETTA G, GIANCARLO, ENRICO F, ARIEL P, IRENE P, DOROTEA R, MISAELE G, TERESA, ABIGAIL, RAFFAELE P, AHARON, NICOLE, PAOLO LUCAS, GLORIA, FRANCESCO Z, CATHERINE EV,  DAVIDE P, EUGENIO, GUGLIELMO, DON FERDINANDO', 'JOSE J - NICO', '0');
# INSERT INTO `arch_prof` VALUES ('13886', '0', 'Hard-Disk', '', '0', '1', '0', '8', '2024-01-09', 'MONTICELLO', 'LUMIX', '', '', '0000-00-00', ' MP4', '0', 'NRVG', '8', 'GITA MEDIE - VISITA MULINO - DENISA, ELISABETTA G, NICOLAS S, GABRIELE P, ENRICO M, RON, ANNA G, DONATA, DEMETRIO E, RAFFAELE S, SELENE F, ISACCO P, DON NICOLA, GIOVANNI L', 'GIOVANNI L', '0');
# INSERT INTO `arch_prof` VALUES ('13887', '0', 'Hard-Disk', '', '0', '1', '0', '62', '2024-02-04', 'ROMA RAI', ' ALTRO', '', '', '0000-00-00', ' H.264', '0', 'NDDE', '62', 'SPECIALE TG1 IL TEMPO DEL RICORDO-LE FOIBE E L ESODO GIULIANO DALMATA   - PARLA ANCHE DEL CAMPO DI FOSSOLI, DI DON ZENO E NOMADELFIA AL MINUTO 32  E 36(IMMAGINI) - ', 'ALTRO', '0');
# INSERT INTO `arch_prof` VALUES ('13888', '0', 'Hard-Disk', '', '0', '1', '0', '7', '2023-12-19', 'NOMADELFIA', ' EDIUS', '', '', '0000-00-00', ' MP4', '0', 'NDDI', '7', 'I TRE DONI DEL GIULARE - SCUOLA MEDIA - DEMETRIO, DENISA, ELISABETTA, RON, DONATA, ISACCO P, ENRICO, NICOLAS, GABRIELE P', 'JOSE J', '0');
# INSERT INTO `arch_prof` VALUES ('13889', '0', 'Hard-Disk', '', '0', '1', '0', '3', '2023-12-31', 'NOMADELFIA', ' EDIUS', '', '', '0000-00-00', ' MP4', '0', 'NDDI', '3', 'AUGURI TANZANIA - DICEMBRE 2023 - MARIO A, ANGELA M, BENEDETTO M, GIOVANNI R, DOROTEA, MARISA F', 'JOSE J', '0');
# INSERT INTO `arch_prof` VALUES ('13890', '0', 'Hard-Disk', '', '0', '1', '0', '12', '2023-12-31', 'NOMADELFIA', ' EDIUS', '', '', '0000-00-00', ' MP4', '0', 'NDDI', '12', 'CRONACA 2023 - VIDEO - 12 MESSI DEL 2023', 'NICO', '0');
# INSERT INTO `arch_prof` VALUES ('13891', '0', 'Hard-Disk', '', '0', '1', '0', '6', '2023-12-31', 'NOMADELFIA', ' EDIUS', '', '', '0000-00-00', ' MP4', '0', 'NDDI', '6', 'POGGETTO - SCENETTA - AHARON M, NADIA, PAOLO FERRETI, FIORELLA, AMABILE, GIUSEPPE Z', 'NICO', '0');
# INSERT INTO `arch_prof` VALUES ('13892', '0', 'Hard-Disk', '', '0', '1', '0', '6', '2023-12-31', 'NOMADELFIA', ' EDIUS', '', '', '0000-00-00', ' MP4', '0', 'NDDI', '6', 'RAGAZZE SCENETTA - NOMA FASHION WEEK - AZZURRA, RACHELLE, MARIA A, BEATRICE F, AGNESE A, NOMEI, DILETTA, GIULIA, MARIA Z, LETIZIA S, DIANA, SARA M, ELENA Z', 'DELETTA', '0');
# INSERT INTO `arch_prof` VALUES ('13893', '0', 'Hard-Disk', '', '0', '1', '0', '6', '2023-12-31', 'NOMADELFIA', ' EDIUS', '', '', '0000-00-00', ' MP4', '0', 'NDDI', '6', 'RAGAZZ1 SCENETTA - RAGAZZI S MEDIA - GABRIEL A, SAMUELE G, GABRIELE Z, DANIELE PA, MAURICE, TARCISIO, ERIK, DAVIDE G, SIMONE L', 'DAVIDE G', '0');
# INSERT INTO `arch_prof` VALUES ('13894', '0', 'Hard-Disk', '', '0', '1', '0', '5', '2023-12-31', 'NOMADELFIA', ' EDIUS', '', '', '0000-00-00', ' MP4', '0', 'NDDI', '5', 'SCENETTA ROSELLANA - BUON ANNO 2024 - MICHELE M, CAMILLA, ZENO S, GABRIELE Z, GIGI, MARCELLA, NOEMI, CARLINO, GIOVANNI Z, EMANUELE, ELENA Z, MARIA Z, MARIA FIORE, GIUSEPPE Z, NICOLE, SILVIA Z, GIOELE M, FRANCESCO Z, DON NICOLA, ALESSIO M, SAMUEL M', 'DON NICOLA', '0');
# INSERT INTO `arch_prof` VALUES ('13895', '0', 'Hard-Disk', '', '0', '1', '0', '64', '2023-12-31', 'NOMADELFIA', ' EDIUS', '', '', '0000-00-00', ' MP4', '0', 'NDDI', '64', 'TUTTE LE SCENETTE - FESTA 2023 - TUTTII GRUPPI', 'ALTRO', '0');
# INSERT INTO `arch_prof` VALUES ('13896', '0', 'Hard-Disk', '', '0', '1', '0', '3', '2024-01-14', 'NOMADELFIA', ' EDIUS', '', '', '0000-00-00', ' MP4', '0', 'NDDI', '3', 'NEWS 01 GENNAIO 2024 - PRESEPI - GLORIA P, GIOLE M, ARIEL, FRANCESO Z, LIVIO, MARIA P, AHARON, NICOLE, RAFFAELE P, LUISA P, PIETRO L, ZAIRA, IRENE P, DON FERDINANDO, MISALE G, ABIGAIL, ANASTASIA, LUISA PA, CAMILLA, ALESSANDRO V, VALENTINA A, NICO, MILVA, DOROTEA, MARISA, DAVIDE P, CATHERINE, DOROTEA R, ISABEL', 'JOSE J', '0');
# INSERT INTO `arch_prof` VALUES ('13897', '0', 'Hard-Disk', '', '0', '1', '0', '4', '2024-01-23', 'NOMADELFIA', ' EDIUS', '', '', '0000-00-00', ' MP4', '0', 'NDDI', '4', '18 GIOVANNI Z - VARIE - MONTAGGIO ', 'SAMUELE G', '0');
# INSERT INTO `arch_prof` VALUES ('13898', '0', 'Hard-Disk', '', '0', '1', '0', '4', '2024-02-03', 'NOMADELFIA', ' EDIUS', '', '', '0000-00-00', ' MP4', '0', 'NDDI', '4', 'NEWS 03 FEBBRAIO 2024 - ESERCIZI SPIRITUALI - ABETONE  - GIANCARLO A, PAOLO F, RACHELLE, DILETTA, RAFFAELE S, DON GIAMPIETRO, CRISTIANA S, ANNA G, FEDERICO E, CARDINALE LOJUDICE, ALESSIO M, DANIELE N, NOEMI, GIULIA A, MARCO F, GIOVANNI Z, DIANA F, MONICA C, MAURICE, RACHELE', 'JOSE J', '0');
# INSERT INTO `arch_prof` VALUES ('13899', '0', 'Hard-Disk', '', '0', '1', '0', '6', '2023-10-07', 'NOMADELFIA', ' EDIUS', '', '', '0000-00-00', ' MP4', '0', 'NDDI', '6', '18 RACHELLE - VARIE - MONTAGGIO FOTO E VIDEO', 'ALTRO', '0');
# INSERT INTO `arch_prof` VALUES ('13900', '0', 'Hard-Disk', '', '0', '1', '0', '20', '2024-01-15', 'NOMADELFIA', ' SONY FS5-K', '', '', '0000-00-00', ' MP4', '0', 'NRCE', '20', 'SALA DON ZENO - MESSA VESCOVO GIOVANNI RONCARI - SELENE F, DON GIAMPIETRO, VESCOVO GIOVANNI RONCARI, TOMMASO N, DON FERDINANDO', 'NICO', '0');
# INSERT INTO `arch_prof` VALUES ('13901', '0', 'Hard-Disk', '', '0', '1', '0', '16', '2024-01-16', 'NOMADELFIA', ' SONY AX-53', '', '', '0000-00-00', ' MP4', '0', 'NREC', '16', 'ESERCIZI RAGAZZI ABETONE - PARTENZA - DON FERDINANDO, DARIO L, RACHELE, SIMONE A, FEDERICO E, LUCA A, NOEMI, DILETTA D, RAFFAELE S, SAMUEL M, DAVIDE G, RACHELE, PAOLO F, AGNESE A, DON GIAMPETRO, MATTEO M, ERIC, GIOVANNI Z, NICOLAS, EMANUELE Z, MARICE, AZZURRA, ASIA, GABRIEL, BEATRICE F, JOSEF', 'JOSE J', '0');
# INSERT INTO `arch_prof` VALUES ('13902', '0', 'Hard-Disk', '', '0', '1', '0', '2', '2024-01-16', 'NOMADELFIA', ' SONY AX-53', '', '', '0000-00-00', ' MP4', '0', 'NRLA', '2', 'LAVORO CAPANONNE - EDILIZIA - PIETRO C, SAMUELE CH, ZENO F, SAMUEL C', 'JOSE J', '0');
# INSERT INTO `arch_prof` VALUES ('13903', '0', 'Hard-Disk', '', '0', '1', '0', '16', '2024-01-17', 'PISTOIA CIMONE', ' SONY AX-53', '', '', '0000-00-00', ' MP4', '0', 'NREC', '16', 'RAGAZZI ABETONE - MEDITAZIONE - ERIC, RAFFAELE S, SAMUEL M, DAVIDE G, RACHELE, PAOLO F, AGNESE A, DON GIAMPETRO, MATTEO M, GIOVANNI Z, NICOLAS, EMANUELE Z, MARICE, AZZURRA, ASIA, GABRIEL, BEATRICE F, JOSEF', 'JOSE J', '0');
# INSERT INTO `arch_prof` VALUES ('13904', '0', 'Hard-Disk', '', '0', '1', '0', '16', '2024-01-18', 'PISTOIA CIMONE', 'LUMIX DJI POCKET 2', '', '', '0000-00-00', ' MP4', '0', 'NREC', '16', 'ADORAZIONE - MESSA - SARA M, MARIA FIORE, DON GIAMPIETRO, NICOLAS, AGNESE A, GIOVANNI Z, ERIC, DILETTA, FRANCESCA G, GIULIA, DANILE N, FEDERICO E, GABRIEL A, MAURICE, DAVIDE G', 'JOSE J', '0');
# INSERT INTO `arch_prof` VALUES ('13905', '0', 'Hard-Disk', '', '0', '1', '0', '23', '2024-01-19', 'PISTOIA CIMONE', 'LUMIX DJI POCKET 2', '', '', '0000-00-00', ' MP4', '0', 'NREC', '23', 'CAMMINO E VISITA MUSEO DELLO SCI - CIMONE - JOY, ELENA Z, SAMUEL M, GABRIELE Z, NAZARENA R, MONICA C, MAURICE, DAVIDE, RACHELLE, DON GIAMPIETRO, GIOVANNI Z, MATTEO M, DANIELE N, LUCA A, SAMUELE G, NICOLAS, RACHELLE, GARIELE L, CRISTIANA S, ODETTE, DANIELE S, DILETTA', 'JOSE J', '0');
# INSERT INTO `arch_prof` VALUES ('13906', '0', 'Hard-Disk', '', '0', '1', '0', '36', '2024-01-20', 'PISTOIA CIMONE ABETONE', ' SONY AX-53 DJI POCKET 2', '', '', '0000-00-00', ' MP4', '0', 'NREC', '36', 'GRIGLIATA ABETONE - CAMMINO, ADORAZIONE, FESTA - DARIO L, SAMUEL MI, NOEMI, DILETTA, GIULIA, TARCISIO, DAVIDE G, MARCO F, ANNA G, MONICA CA, ODETTE, JOSE JUAN, ERIK, NICOLAS, RAFAELE S, PAOLO F, RACHELLE, MATTEO O, LUCA A, SIMONE L, DAMIANO L, SARA MI, MARIA A, DON GIAMPIETRO, RACHELE, AZZURRA, LUCA N, DANIELE S, SAMUELE G, JOSEF, GIOVANNI Z, DANIELE N, FEDERICO E,  ALLY, DIANA, AGNESE, MAURICE', 'JOSE J', '0');
# INSERT INTO `arch_prof` VALUES ('13907', '0', 'Hard-Disk', '', '0', '1', '0', '60', '2024-01-21', 'PISTOIA CIMONE', ' SONY AX-53 DJI POCKET 2 GOPRO', '', '', '0000-00-00', ' MP4', '0', 'NREC', '60', 'ABETONE SCI CENA AMICI POLIZIA - PISTE SCI, CENA - SAMUELE G, RAFFAELE S, BEATRICE F, STEFAN, RACHELLE, JOSEF, DILETTA, JOY, MAURICE, EMMANUELE, FEDERICO E, RACHELE, NOEMI, RUGGIERO, NAZARENA R, ANNA G, DON GIAMPIETRO, ELENA Z, DARIO L, ANNA G, GIULIA, DAVIDE G, ERIC, GIOVANNI Z, GABRIEL A, DANIELE N, CRISTIANA, DANIELE PA, PAOLO F, SARA MI ', 'JOSE J', '0');
# INSERT INTO `arch_prof` VALUES ('13908', '0', 'Hard-Disk', '', '0', '1', '0', '180', '2024-01-22', 'PISTOIA CIMONE', ' SONY AX-53 DJI POCKET 2', '', '', '0000-00-00', ' MP4', '0', 'NREC', '180', 'CARDINALE LOJUDICE ESERCIZI RAGAZZI - MESSA, VISITA CARDINALE LOJUDICE - BETARICE F, SAMUELE MI, FEDERICO E, NOEMI, POLIZIA, RACHELLE, MAURICE, CARDINALE AUGISTO LOJUDICE, DON GIAMPIETRO, PAOLO F, TARCISIO M, MONICA CA, RACHELLE, DIANA F, FRANCESCA G', 'JOSE J', '0');
# INSERT INTO `arch_prof` VALUES ('13909', '0', 'Hard-Disk', '', '0', '1', '0', '10', '2024-01-23', 'PISTOIA CIMONE', ' SONY AX-53', '', '', '0000-00-00', ' MP4', '0', 'NREC', '10', 'PREGHIERA E PISTA SCI - PARTENZA, 18 GIOVANNI Z - FEDERICO E, DANIELE N, CRISTIANA, MONICA CA, MARCO F, NICOLAS, DARIO L, MATTEO M, DAMIANO L, SAMUEL MI, SIMONE A, GABRIELE Z, GIOVANNI Z, ELENA Z', 'JOSE J', '0');
# INSERT INTO `arch_prof` VALUES ('13910', '0', 'Hard-Disk', '', '0', '1', '0', '34', '2024-01-24', 'ROMA ', ' SONY AX-53', '', '', '0000-00-00', ' MP4', '0', 'NREC', '34', 'CARD. ZUPPI ESERCIZI - CENTRO DI SPIRITO, MESA - MARIA SERENA, PIETRO L, ZENO S, DON FERDINANDO, GIANCARLO, LUISA P, LUISA PA, MAURIZIO C, FRANCESCO A, DON VIRGINIO, CARD. MATTEO ZUPPI, LUCIA, DON GIOVANNI, ONORATO, FRANCESCO ANT, ROSELLA, SERENA A, CHIARA L, GIORGIO GIBERTINI ', 'CARLO M', '0');
# INSERT INTO `arch_prof` VALUES ('13911', '0', 'Hard-Disk', '', '0', '1', '0', '39', '2024-01-24', 'PISTOIA CIMONE', ' SONY AX-53', '', '', '0000-00-00', ' MP4', '0', 'NREC', '39', 'FESTA E MESSA CONCLUSIVA - CONCLUSIONE, SCENETTE - MAURICE, DILETTA, MELISSA, MATTEO M, DANIELE N, DON GIAMPIETRO, ANNA G, ODETTE, TARCISIO, PAOLO F, GIOVANNI Z, FRANCESCA, MARIA FIORE, SIMONE L, JOY, RACHELLE, BENEDETTO, NOEMI, MONICA CA, ALESSIO MI, DANIELE PA, AZZURRA, SAMUELE G, MARCO F, SARA MI, DIANA, MARIA FIORE, MARIA A, RAFFAELE S, CRISTIANA, LUCA NA, ALLY, RACHELLE, CATERINA, GABRIELE Z', 'JOSE J', '0');
# INSERT INTO `arch_prof` VALUES ('13912', '0', 'Hard-Disk', '', '0', '1', '0', '4', '2024-01-25', 'PISTOIA CIMONE', ' SONY AX-53', '', '', '0000-00-00', ' MP4', '0', 'NREC', '4', 'PARTENZA - GRUPPO - PAOLO F, DON GIAMPIETRO, FEDERICO E, JOSE JUAN, ANNA G, RAFFAELE S, NICOLAS, AZZURRA, JOSEF, MARIA FIORE, ANNA C, LUCA A, DILETTA, NOEMI, RACHELLE, SARA MI, DIANA, ', 'JOSE J', '0');
# INSERT INTO `arch_prof` VALUES ('13913', '0', 'Hard-Disk', '', '0', '1', '0', '46', '2024-02-01', 'ROMA', 'OBS', '', '', '0000-00-00', 'MKV', '0', 'NREC', '46', 'CARD. LOJUDICE ESERCIZI A ROMA - ESERCIZI SPIRITUALI - CARD. LOJUDICE, GIANCARLO', 'STEFANO A', '0');
# INSERT INTO `arch_prof` VALUES ('13914', '0', 'Hard-Disk', '', '0', '1', '0', '49', '2024-02-04', 'NOMADELFIA', ' SONY FS5-K', '', '', '0000-00-00', ' MXF', '0', 'NRIN', '49', 'INTERVISTA SU PINO ARPIONI PIETRO FEDERICO, NICO, ELENA - INTERVISTE GRUPPO BETLEM ALTO - PIETRO L, FEDERICO E, NICO, ELENA F', 'NICO', '0');
# INSERT INTO `arch_prof` VALUES ('13915', '0', 'Hard-Disk', '', '0', '1', '0', '12', '2024-02-06', 'NOMADELFIA', ' SONY FS5-K', '', '', '0000-00-00', ' MXF', '0', 'NRLA', '12', 'PAVIMENTAZIONE CAPANNONE OFFICINA - LAVORI - ZENO F, CARLINO, MISAELE, GIOELE MI, GIULIO C, CATERIN, GLORIA, AMOS, ARIEL, STEFANO Z, ADOMAS, GIOIA M, LUCIA M, CHANTAL, ISMAELE S, RAFFAELE P, AHARON, ABIGAIL, PAOLO LUCAS, TERESA, NICOLE, SARA M, SERENA A, PIETRO C', 'NICO', '0');
# INSERT INTO `arch_prof` VALUES ('13916', '0', 'Hard-Disk', '', '0', '1', '0', '28', '2024-02-10', 'NOMADELFIA', ' SONY AX-53 SONY FS5-K', '', '', '0000-00-00', ' MP4 MXF', '0', 'NRFE', '28', 'FESTA CARNEVALE - BAR, RETTANGOLONE - SUSANNA R, NICOLE, CAMILLA M, TERESA, RAFFAELE P, MIRIAM F, MARICA, STEFANO A, ISABEL, DANIELE N, SEBASTIANO, GLORIA, PIETRO C, CHIARA P, MARIA P, MAURICE, DAVIDE P, ELISABETTA, GIOVANNI L, GIUSEPPE G, SIMONE P, DARIO L, NATAN, SAMUEL MI, SAMUELE G, MIRIO, CRISTIANA S, MORENA, AURORA, CHIRARA L, MANUELA, BEATRICE F, FEDERICO E, ELENA F, MIRIAM, SOFIA F, MARCO F, DENISA, SELENE, JOY, DAVIDE G, SIMONE A, GIOVANNI Z, NAZARENA R, DANIANO L, MATTEO M, LUISA PA, AHARON, MARIA CA, LUCIA M, NOEMI, ENRICO M, ASIA, GABRIELE Z, RAFFAELE S, DOROTEA R, ISMAELE S, ALESSANDRO V, DON NICOLA, LETIZIA G, SANDRO D, ROBERTO N, MARY, ELISA F, ELENA Z, SARA M, DON NICOLA, BENEDETTO L, CHANTAL, FEDERICA P', 'NICO - JOSE J', '0');
# INSERT INTO `arch_prof` VALUES ('13918', '0', 'Hard-Disk', '', '0', '1', '0', '14', '2024-02-14', '?', 'PANASONIC', '', '', '0000-00-00', ' MP4', '0', 'NRGE', '14', 'FUNERALE JUSFI VD - FUNERAL - NAZARENA R, NICO, ALESSANDRO V, TIZIANA F, TIZIANO G, PAOLO TAVERNELLI, FEDERICO E, GIOVANNI A, SOFIA F', 'CARLO M', '0');
# INSERT INTO `arch_prof` VALUES ('13919', '0', 'Hard-Disk', '', '0', '1', '0', '97', '2024-02-17', 'NOMADELFIA', ' ALTRO', '', '', '0000-00-00', ' MP4', '0', 'NREC', '97', 'CARD LOJUDICE 3ZO TURNO ESERCIZI SPIRITUALI - VISITA - CARD. PAOLO LOJUDICE, DON FERDIANDO, GIANCARLO, MARIO STAMPA, MARCO O, NATALIA S, REZIO', 'NICO', '0');
#

CREATE TABLE `categ_arch_prof` (
  `Id_categoria_arch_prof` int(11) NOT NULL AUTO_INCREMENT COMMENT 'Id categoria',
  `Cat_arch_prof` varchar(2) NOT NULL COMMENT 'Serie',
  `Sotto_cat_arch_prof` varchar(2) NOT NULL COMMENT 'Categoria',
  `Descrizione` varchar(100) NOT NULL COMMENT 'Descrizione categoria',
  PRIMARY KEY (`Id_categoria_arch_prof`),
  UNIQUE KEY `categoria` (`Descrizione`),
  UNIQUE KEY `Id_categoria_arch_prof` (`Id_categoria_arch_prof`,`Cat_arch_prof`,`Sotto_cat_arch_prof`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=20 DEFAULT CHARSET=utf8;


INSERT INTO `categ_arch_prof` VALUES ('1', 'NR', 'CE', 'REGISTRAZIONE CERIMONIE S.MESSE,MATRIMONI,BATTESIMI ECC.');
INSERT INTO `categ_arch_prof` VALUES ('2', 'ND', 'DE', 'SERVIZI E INTERVISTE SU NOM. REALIZZATI DA ALTRI');
INSERT INTO `categ_arch_prof` VALUES ('3', 'ND', 'DI', 'SERVIZI MONTATI REALIZZATI DA NOMADELFIA');
INSERT INTO `categ_arch_prof` VALUES ('4', 'NR', 'GE', 'RIPRESE GENERICHE');
INSERT INTO `categ_arch_prof` VALUES ('5', 'ND', 'IN', 'INCONTRO E INTERVISTE');
INSERT INTO `categ_arch_prof` VALUES ('6', 'NR', 'LA', 'REGISTRAZIONE LAVORO');
INSERT INTO `categ_arch_prof` VALUES ('7', 'NR', 'SP', 'REGISTRAZIONE SPETTACOLI');
INSERT INTO `categ_arch_prof` VALUES ('8', 'NR', 'VG', 'REGISTRAZIONE VISITE GITE');
INSERT INTO `categ_arch_prof` VALUES ('9', 'NS', 'SE', 'REGISTRAZIONE SERATE DI NOMADELFIA');
INSERT INTO `categ_arch_prof` VALUES ('10', 'NR', 'CU', 'REGISTRAZIONE CULTURA');
INSERT INTO `categ_arch_prof` VALUES ('11', 'NR', 'MU', 'REGISTRAZIONE MUSICAL');
INSERT INTO `categ_arch_prof` VALUES ('12', 'NR', 'GR', 'REGISTRAZIONE GRUPPI FAMILIARE E PERSONE');
INSERT INTO `categ_arch_prof` VALUES ('13', 'NR', 'IN', 'REGISTRAZIONE INTERVISTE');
INSERT INTO `categ_arch_prof` VALUES ('14', 'NR', 'FE', 'REGISTRAZIONE FESTE');
INSERT INTO `categ_arch_prof` VALUES ('15', 'NR', 'SC', 'REGISTRAZIONE SCUOLA FAMILIARE');
INSERT INTO `categ_arch_prof` VALUES ('16', 'NR', 'SP', 'REGISTRAZIONE ATTIVITA SPORTIVA');
INSERT INTO `categ_arch_prof` VALUES ('17', 'NR', 'EC', 'REGISTRAZIONE ESERCIZI SPIRITUALI E CAMMINO');
INSERT INTO `categ_arch_prof` VALUES ('18', 'NR', 'TZ', 'TANZANIA');
INSERT INTO `categ_arch_prof` VALUES ('19', 'NR', 'PN', 'PANORAMICHE');


CREATE TABLE `categ_trasm_tv` (
  `id_serie` int(11) NOT NULL AUTO_INCREMENT,
  `sigla_serie` varchar(5) NOT NULL,
  `desc_serie` varchar(512) NOT NULL,
  PRIMARY KEY (`id_serie`),
  KEY `sigla_serie` (`sigla_serie`),
  KEY `desc_serie` (`desc_serie`(255))
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;


INSERT INTO `categ_trasm_tv` VALUES ('1', 'AM', 'AMBIENTE: NATURA, ARCHITETTURA, EGOLOGIA, TECNICA');
INSERT INTO `categ_trasm_tv` VALUES ('2', 'AN', 'ANIMALI');
INSERT INTO `categ_trasm_tv` VALUES ('3', 'AT', 'ATTUALITA: POLITICA, RELIGIOSE, COSTUME, ECC');
INSERT INTO `categ_trasm_tv` VALUES ('4', 'CI', 'CIVILTA : STORIA, ARTE, RELIGIONE');
INSERT INTO `categ_trasm_tv` VALUES ('5', 'FA', 'FILM ARCHIVIO');
INSERT INTO `categ_trasm_tv` VALUES ('6', 'MU', 'MUSICA: CLASSICA, SINFONICA, LEGGERA, DANZA');
INSERT INTO `categ_trasm_tv` VALUES ('7', 'SP', 'SPETTACOLI VARI: COMCHE, COMMEDIA, CIRCO, PATTINAGGIO, ECC');
INSERT INTO `categ_trasm_tv` VALUES ('8', 'NO', 'FILM SCARTATI - NON VISIBILI');
INSERT INTO `categ_trasm_tv` VALUES ('9', 'TUTTE', 'TUTTE LE SERIE');


CREATE TABLE `categoria` (
  `id_categoria` int(10) NOT NULL AUTO_INCREMENT,
  `desc_categoria` varchar(25) NOT NULL,
  PRIMARY KEY (`id_categoria`),
  UNIQUE KEY `des_categoria` (`desc_categoria`),
  KEY `des_categoria_2` (`desc_categoria`)
) ENGINE=InnoDB AUTO_INCREMENT=35 DEFAULT CHARSET=utf8;


INSERT INTO `categoria` VALUES ('29', 'AmAstronomia');
INSERT INTO `categoria` VALUES ('27', 'AmEcologia');
INSERT INTO `categoria` VALUES ('26', 'AmNatura');
INSERT INTO `categoria` VALUES ('28', 'AnAnimali');
INSERT INTO `categoria` VALUES ('19', 'CiAC');
INSERT INTO `categoria` VALUES ('21', 'CiContemporanea');
INSERT INTO `categoria` VALUES ('23', 'CiGenerale');
INSERT INTO `categoria` VALUES ('22', 'CiMedioevoRinascimento');
INSERT INTO `categoria` VALUES ('25', 'CiNonClass');
INSERT INTO `categoria` VALUES ('24', 'CiReligione');
INSERT INTO `categoria` VALUES ('20', 'CiRisorgimento');
INSERT INTO `categoria` VALUES ('14', 'FaNonClass');
INSERT INTO `categoria` VALUES ('17', 'FiAnimazione');
INSERT INTO `categoria` VALUES ('7', 'FiAvventura');
INSERT INTO `categoria` VALUES ('5', 'FiAzione');
INSERT INTO `categoria` VALUES ('2', 'FiComico');
INSERT INTO `categoria` VALUES ('3', 'FiCommedia');
INSERT INTO `categoria` VALUES ('18', 'FiDocumentario');
INSERT INTO `categoria` VALUES ('9', 'FiDrammatico');
INSERT INTO `categoria` VALUES ('10', 'FiFantascienza');
INSERT INTO `categoria` VALUES ('11', 'FiMusical');
INSERT INTO `categoria` VALUES ('6', 'FiNonClass');
INSERT INTO `categoria` VALUES ('16', 'FiPoliziesco');
INSERT INTO `categoria` VALUES ('1', 'FiReligiosi');
INSERT INTO `categoria` VALUES ('15', 'FiRomantico');
INSERT INTO `categoria` VALUES ('13', 'FiSportivo');
INSERT INTO `categoria` VALUES ('4', 'FiStorico');
INSERT INTO `categoria` VALUES ('12', 'FiThriller');
INSERT INTO `categoria` VALUES ('8', 'FiWestern');
INSERT INTO `categoria` VALUES ('31', 'MuClassica');
INSERT INTO `categoria` VALUES ('30', 'MuLeggera');
INSERT INTO `categoria` VALUES ('32', 'MuNonClass');
INSERT INTO `categoria` VALUES ('34', 'SpComico');
INSERT INTO `categoria` VALUES ('33', 'SpNonClass');


CREATE TABLE `critica` (
  `id_critica` int(10) NOT NULL AUTO_INCREMENT,
  `desc_critica` varchar(25) NOT NULL,
  PRIMARY KEY (`id_critica`),
  UNIQUE KEY `des_critica` (`desc_critica`),
  KEY `des_critica_2` (`desc_critica`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;


INSERT INTO `critica` VALUES ('6', 'ACCETABILE');
INSERT INTO `critica` VALUES ('7', 'BUONO');
INSERT INTO `critica` VALUES ('9', 'ECCELLENTE');
INSERT INTO `critica` VALUES ('8', 'OTTIMO');
INSERT INTO `critica` VALUES ('0', 'SENZA');

CREATE TABLE `load_film` (
  `descrizione` varchar(200) NOT NULL,
  `Serie_l` varchar(2) DEFAULT NULL,
  `Numero_l` int(6) DEFAULT NULL,
  PRIMARY KEY (`descrizione`),
  KEY `Index Descrizione` (`descrizione`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


INSERT INTO `load_film` VALUES ('FA3964 ZORRO L  ESPERTO D  ARTE ITALIANO STAGIONE 2.MP4\r', 'FA', '3964');
INSERT INTO `load_film` VALUES ('FA3965 SIMPATICHE CANAGLIE UN MULO IN AUTOMOBILE.MP4\r', 'FA', '3965');

CREATE TABLE `trasmissioni_tv` (
  `trasmissioni_tv_ID` int(11) NOT NULL AUTO_INCREMENT,
  `Series` varchar(2) NOT NULL COMMENT 'Serie Film',
  `Numeros` int(5) NOT NULL COMMENT 'Numero Film',
  `Record` int(2) DEFAULT '1' COMMENT 'Record progressivo nella cassetta',
  `Ini` int(3) DEFAULT '0' COMMENT 'Inizio minutaggio del video nella cassetta',
  `Fin` int(3) DEFAULT NULL COMMENT 'Fine dei minuti del video nella cassetta',
  `DataReg` date DEFAULT NULL COMMENT 'La data di registrazione',
  `Visione` enum('Tutti','14Anni','Elementari','12Anni','Superiori','NonVisibile','Medie','NonVisionato') DEFAULT NULL COMMENT 'Categorie di visione',
  `Critica` enum('0','6','7','8','9','10') DEFAULT NULL COMMENT 'Giudizio critico di valutazione da 6(min)-9(max).',
  `Visionatore` int(2) NOT NULL COMMENT 'Referenza esterna,Nome del visionatore del film',
  `UTrasm` date DEFAULT NULL COMMENT 'Ultima trasmissione del video',
  `Supporto` enum('VHS','DVD','SD','HD','FILE','DVD FILE','MANCA') DEFAULT NULL COMMENT 'Il supporto del video',
  `Cat` enum('FiReligiosi','FiComico','FiCommedia','FiStorico','FiAzione','FiAvventura','FiWestern','FiDrammatico','FiFantascienza','FiMusical','FiThriller','FiSportivo','FiRomantico','FiPoliziesco','FiAnimazione','FiDocumentario','CiAC','CiRisorgimento','CiContemporanea','CiMedioevoRinascimento','CiGenerale','CiReligione','CiNonClass','AmNatura','AmEcologia','AnAnimali','AmAstronomia','MuLeggera','MuClassica','MuNonClass','SpNonClass','SpComico') DEFAULT NULL COMMENT 'Categoria storiche del video',
  `Min` int(3) DEFAULT NULL COMMENT 'Minuti durata video',
  `Descriz` text COMMENT 'Descrizione e titolo del video',
  `Note` varchar(300) NOT NULL COMMENT 'Note di riferimento al film',
  `link` varchar(1000) NOT NULL COMMENT 'Link Trial',
  PRIMARY KEY (`trasmissioni_tv_ID`),
  UNIQUE KEY `Unique Key` (`Series`,`Numeros`,`Record`) USING BTREE,
  KEY `Index by Serie` (`Series`) USING BTREE,
  KEY `Index by Numero` (`Numeros`) USING BTREE,
  KEY `Index by Link` (`link`(255)) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=13863 DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT COMMENT='Registra le trasmissioni registrate';


CREATE TABLE `prestiti_film` (
  `Id_pres` int(11) NOT NULL AUTO_INCREMENT COMMENT 'id prestiti',
  `Id_film` int(11) NOT NULL COMMENT 'Identificazione Film',
  `Serie` varchar(2) NOT NULL COMMENT 'Serie',
  `Numero` varchar(5) NOT NULL COMMENT 'Numero',
  `Data_Pres` date NOT NULL COMMENT 'Data Prestiti',
  `Data_Rest` date NOT NULL COMMENT 'Data Restituido',
  `Nome_Prest` varchar(30) NOT NULL COMMENT 'Persona consegnate',
  PRIMARY KEY (`Id_pres`),
  KEY `Id_film` (`Id_film`),
  KEY `Serie` (`Serie`),
  KEY `Numero` (`Numero`),
  KEY `Nome_Prest` (`Nome_Prest`),
  KEY `Data_Rest` (`Data_Rest`),
  KEY `Data_Pres` (`Data_Pres`),
  CONSTRAINT `prestiti_film_ibfk_1` FOREIGN KEY (`Id_film`) REFERENCES `trasmissioni_tv` (`trasmissioni_tv_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2841 DEFAULT CHARSET=utf8;


CREATE TABLE `progr_settima` (
  `Id_proset` int(9) NOT NULL AUTO_INCREMENT COMMENT 'Id prog sett',
  `Data_trasm` date NOT NULL COMMENT 'Data Trasmissione',
  `Numset` varchar(2) NOT NULL COMMENT 'Numero Settima',
  `Nomgio` varchar(20) NOT NULL COMMENT 'Nome giorino',
  `Tv` varchar(10) NOT NULL COMMENT 'Canale Trasmissione',
  `Ora_trasm` time NOT NULL COMMENT 'Ora Trasmissione',
  `Visione` varchar(20) NOT NULL COMMENT 'Tipo visione',
  `Serie` varchar(2) NOT NULL COMMENT 'Serie Film',
  `Numero` int(5) NOT NULL COMMENT 'Numero film',
  `Descrizione` varchar(200) NOT NULL COMMENT 'Titolo/Descrizione film',
  PRIMARY KEY (`Id_proset`),
  KEY `Data_trasm` (`Data_trasm`),
  KEY `Descrizione` (`Descrizione`)
) ENGINE=InnoDB AUTO_INCREMENT=42 DEFAULT CHARSET=utf8;


CREATE TABLE `storico_trasmissioni` (
  `trasmissioni_tv_ID` int(11) NOT NULL COMMENT 'Referenza a id nella tabella trasmissioni_tv',
  `DataTrasm` date NOT NULL,
  PRIMARY KEY (`trasmissioni_tv_ID`,`DataTrasm`) USING BTREE,
  CONSTRAINT `storico_trasmissioni_ibfk_1` FOREIGN KEY (`trasmissioni_tv_ID`) REFERENCES `trasmissioni_tv` (`trasmissioni_tv_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Mantiene lo storico dei film trasmessi.';

CREATE TABLE `supporto` (
  `id_supporto` int(10) NOT NULL AUTO_INCREMENT,
  `des_supporto` varchar(25) NOT NULL,
  PRIMARY KEY (`id_supporto`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8;


INSERT INTO `supporto` VALUES ('0', 'MANCA');
INSERT INTO `supporto` VALUES ('1', 'VHS');
INSERT INTO `supporto` VALUES ('2', 'DVD');
INSERT INTO `supporto` VALUES ('3', 'SD');
INSERT INTO `supporto` VALUES ('4', 'HD');
INSERT INTO `supporto` VALUES ('5', 'FILE');
INSERT INTO `supporto` VALUES ('6', 'DVD FILE');



CREATE TABLE `vecchio_tv` (
  `trasmissioni_tv_ID` int(11) NOT NULL AUTO_INCREMENT,
  `Serie` varchar(12) CHARACTER SET latin1 DEFAULT NULL COMMENT '(FA=film, SP=spettacoli, CI= vivilta..)',
  `Record` int(2) DEFAULT '1' COMMENT 'Record progressivo nella cassetta',
  `Ini` int(3) DEFAULT '0' COMMENT 'Inizio minutaggio del video nella cassetta',
  `Fin` int(3) DEFAULT NULL COMMENT 'Fine dei minuti del video nella cassetta',
  `DataReg` date DEFAULT NULL COMMENT 'La data di registrazione',
  `Visione` enum('Tutti','14Anni','Elementari','12Anni','Superiori','NonVisibile','Medie','NonVisionato') CHARACTER SET latin1 DEFAULT NULL COMMENT 'Categorie di visione',
  `Critica` enum('6','7','8','9','10') CHARACTER SET latin1 DEFAULT NULL COMMENT 'Giudizio critico di valutazione da 6(min)-9(max).',
  `Visionatore` int(2) NOT NULL COMMENT 'Referenza esterna,Nome del visionatore del film',
  `UTrasm` date DEFAULT NULL COMMENT 'Ultima trasmissione del video',
  `Supporto` enum('VHS','DVD') CHARACTER SET latin1 DEFAULT NULL COMMENT 'Il supporto del video',
  `Cat` enum('FiReligiosi','FiComico','FiCommedia','FiStorico','FiAzione','FiNonClass','FiAvventura','FiWestern','FiDrammatico','FiFantascienza','CiAC','CiRisorgimento','CiContemporanea','CiMedioevoRinascimento','AmNatura','AmEcologia','AnAnimali','AmAstronomia','CiGenerale','CiReligione','CiNonClass','FaNonClass','MuLeggera','MuClassica','MuNonClass','SpNonClass','SpComici') CHARACTER SET latin1 DEFAULT NULL COMMENT 'Categoria storiche del video',
  `Min` int(3) DEFAULT NULL COMMENT 'Minuti durata video',
  `Desciz` text CHARACTER SET latin1 COMMENT 'Descrizione e titolo del video',
  PRIMARY KEY (`trasmissioni_tv_ID`),
  KEY `Visionatore` (`Visionatore`)
) ENGINE=InnoDB AUTO_INCREMENT=12923 DEFAULT CHARSET=utf8 COMMENT='Registra le trasmissioni registrate';

CREATE TABLE `visionatori` (
  `idVisionatore` int(11) NOT NULL AUTO_INCREMENT COMMENT 'ID del Visionatore, ha una referenza in archvio_tv',
  `Nome` varchar(50) CHARACTER SET latin1 NOT NULL COMMENT 'Nome del visionatore',
  PRIMARY KEY (`idVisionatore`)
) ENGINE=InnoDB AUTO_INCREMENT=29 DEFAULT CHARSET=utf8 COMMENT='Contiene l''id e il nome del visionatore del film';

INSERT INTO `visionatori` VALUES ('0', 'Senza');
INSERT INTO `visionatori` VALUES ('1', 'Elena F.');
INSERT INTO `visionatori` VALUES ('2', 'GianniBusto');
INSERT INTO `visionatori` VALUES ('3', 'Carlo M.');
INSERT INTO `visionatori` VALUES ('4', 'Ireneo');
INSERT INTO `visionatori` VALUES ('5', 'Roberto N.');
INSERT INTO `visionatori` VALUES ('6', 'Giordano');
INSERT INTO `visionatori` VALUES ('7', 'Mara');
INSERT INTO `visionatori` VALUES ('8', 'Domenico');
INSERT INTO `visionatori` VALUES ('9', 'Lice');
INSERT INTO `visionatori` VALUES ('10', 'Maria Giovanna');
INSERT INTO `visionatori` VALUES ('11', 'Nico');
INSERT INTO `visionatori` VALUES ('12', 'Piero');
INSERT INTO `visionatori` VALUES ('13', 'Maria C.');
INSERT INTO `visionatori` VALUES ('14', 'Sabrina');
INSERT INTO `visionatori` VALUES ('15', 'Tommaso');
INSERT INTO `visionatori` VALUES ('16', 'Livio');
INSERT INTO `visionatori` VALUES ('17', 'Antonietta');
INSERT INTO `visionatori` VALUES ('18', 'Donatella');
INSERT INTO `visionatori` VALUES ('19', 'Mina');
INSERT INTO `visionatori` VALUES ('20', 'Altri');
INSERT INTO `visionatori` VALUES ('21', 'Zeno S.');
INSERT INTO `visionatori` VALUES ('22', 'Franco');
INSERT INTO `visionatori` VALUES ('23', 'Pietro L.');
INSERT INTO `visionatori` VALUES ('24', 'Nazzarena R.');
INSERT INTO `visionatori` VALUES ('25', 'Giovanni A');
INSERT INTO `visionatori` VALUES ('26', 'Chiara L');
INSERT INTO `visionatori` VALUES ('27', 'Stella G');
INSERT INTO `visionatori` VALUES ('28', 'Marcella M');


CREATE TABLE `visione` (
  `id_visione` int(10) NOT NULL AUTO_INCREMENT,
  `desc_visione` varchar(23) NOT NULL,
  PRIMARY KEY (`id_visione`),
  UNIQUE KEY `d_visione` (`desc_visione`),
  KEY `d_visione_2` (`desc_visione`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8;


INSERT INTO `visione` VALUES ('4', '12Anni');
INSERT INTO `visione` VALUES ('2', '14Anni');
INSERT INTO `visione` VALUES ('3', 'Elementari');
INSERT INTO `visione` VALUES ('6', 'Medie');
INSERT INTO `visione` VALUES ('7', 'NonVisibile');
INSERT INTO `visione` VALUES ('8', 'NonVisionato');
INSERT INTO `visione` VALUES ('5', 'Superiori');
INSERT INTO `visione` VALUES ('1', 'Tutti');

