name: Laravel

on: push

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:10.4
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: root
        ports:
          - 32574:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    env:
      DB_HOST: 127.0.0.1
      DB_PORT: 32574
    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.1'
    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: cd sin && composer install  --ignore-platform-req=ext-gd --ignore-platform-req=ext-exif
    - name: Clear Config
      run: cd sin && php artisan config:clear
    - name: Run tests
      run: cd sin &&  ./vendor/bin/pest
