name: run_tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-22.04
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.1

    services:
      # NOTE: the container name is the same of the docker-compose.yml in order to
      # have the same .env.testing file working fot both laravel Sail and github actions.
      mysql-test:
        image: mariadb:10.4
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: root
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          version: 3.x

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache/files
          key: cache-laravel-composer-${{ hashFiles('composer.json') }}

      - name: Install composer deps
        run: composer install  --ignore-platform-req=ext-gd --ignore-platform-req=ext-exif

      - name: Prepare Laravel Application
        run: |
          cp .env.ci .env
          php artisan key:generate

      - name: Run tests
        run: task test
