name: run_linter

on:
  push:
    paths:
      - '**.php'

jobs:
  phplint:
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.2

    steps:
      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          version: 3.x

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Install composer deps
        run: composer install  --ignore-platform-req=ext-gd --ignore-platform-req=ext-exif

      - name: Install npm deps
        run: npm install

      - run: task lint:check:ci

      - run: task analyse
