name: run_tests

on:
  push:
  pull_request:
    types: [opened, reopened]

jobs:
  test:
    runs-on: ubuntu-22.04
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.1

    services:
      # NOTE: the container name is the same of the docker-compose.yml in order to
      # have the same .env.testing file working fot both laravel Sail and github actions.
      mysql-test:
        image: mariadb:10.4
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: root
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Install exiftool
        # TODO: the exif tool version is hardcoded 12.64. Make it as the same version of the EXIFTOOL_VERSION=12.64 in the dockerfile
        run: |
          apt-get update && \
          apt-get install -y wget make && \
          wget https://exiftool.org/Image-ExifTool-13.17.tar.gz && tar -xzvf Image-ExifTool-13.17.tar.gz &&  rm -rf Image-ExifTool-13.17.tar.gz && \
          cd Image-ExifTool-13.17  && \
          perl Makefile.PL && \
          make install && \
          exiftool -ver
       #   rm -rf Image-ExifTool-*.tar.gz && \

      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          version: 3.x

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache/files
          key: cache-laravel-composer-${{ hashFiles('composer.json') }}

      - name: Install composer deps
        run: composer install  --ignore-platform-req=ext-gd --ignore-platform-req=ext-exif

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install npm deps
        run: npm install

      - name: Prepare Laravel Application
        run: |
          cp .env.ci .env
          php artisan key:generate

      - name: Run tests
        run: task test:ci
