name: run_tests

on:
  push:
  pull_request:
    types: [opened, reopened]

jobs:
  test:
    runs-on: ubuntu-22.04
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.2
    env:
      EXIFTOOL_VERSION: 13.38  # Change also the EXIFTOOL_VERSION in the dockerfile

    services:
      # NOTE: the container name is the same of the docker-compose.yml in order to
      # have the same .env.testing file working fot both laravel Sail and github actions.
      mysql-test:
        image: mariadb:10.4
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: root
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Fix APT repository label change issue
        run: |
          apt-get update --allow-releaseinfo-change

      - name: Install exiftool
        run: |
          apt-get update && \
          apt-get install -y wget make && \
          wget https://exiftool.org/Image-ExifTool-${{ env.EXIFTOOL_VERSION }}.tar.gz && tar -xzvf Image-ExifTool-${{ env.EXIFTOOL_VERSION }}.tar.gz &&  rm -rf Image-ExifTool-${{ env.EXIFTOOL_VERSION }}.tar.gz && \
          cd Image-ExifTool-${{ env.EXIFTOOL_VERSION }}  && \
          perl Makefile.PL && \
          make install && \
          exiftool -ver

      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          version: 3.x

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache/files
          key: cache-laravel-composer-${{ hashFiles('composer.json') }}

      - name: Install composer deps
        run: composer install  --ignore-platform-req=ext-gd --ignore-platform-req=ext-exif

      - name: Install puppeteer dependencies
        run: |
          apt install -y ca-certificates fonts-liberation libasound2 libatk-bridge2.0-0 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgbm1 libgcc1 libglib2.0-0 libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 lsb-release wget xdg-utils

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install npm deps
        run: npm install

      - name: Prepare Laravel Application
        run: |
          cp .env.ci .env
          php artisan key:generate

      - name: Start Laravel Server
        run: php artisan serve --host=0.0.0.0 --port=80 &

      - name: Wait for Laravel Server to be ready
        run: |
          apt-get install -y wait-for-it
          wait-for-it 127.0.0.1:80 --timeout=60 --strict -- echo "Laravel Server is up"

      - name: Run tests
        run: task test:ci
