name: tests

on: push

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.1

    services:
     # NOTE: the container name is the same of the docker-compose.yml in order to
     # have the same .env.testing file working fot both laravel Sail and github actions.
      mysql-test:
        image: mariadb:10.4
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: root
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.1'

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
          path: ~/.composer/cache/files
          key: dependencies-laravel-composer-${{ hashFiles('composer.json') }}

    - name: Install Dependencies
      run: cd sin && composer install  --ignore-platform-req=ext-gd --ignore-platform-req=ext-exif

    - name: Prepare Laravel Application
      run: |
        cd sin 
        php artisan key:generate --env=testing

    - name: Clear Config
      run: cd sin && php artisan config:clear

    - name: Run tests
      run: cd sin && ./vendor/bin/pest
